= Appendix: REST API Examples
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book

xref:appendix.adoc[← Back to Appendix]

ONTAP REST API examples for authentication, FlexGroup volume creation, deletion, network interfaces, SnapMirror, NFS server configuration, and export policy rules.


[[rest-api-examples-for-testing]]
== REST API examples for testing.

The following section shows example REST API calls for cluster operations. These can be used alongside or in lieu of current automation suites being used with unified ONTAP. These APIs cover the following standard administration scenarios. A Linux machine is required to use these scripts. Bash and curl are required to use the scripts.

The examples include:

* <<create-flexgroup-volume,Creating>> and <<delete-volumes,deleting>> FlexGroup volumes.
* <<data-interfaces,Creating and deleting a network interface>>.
* <<create-and-initialize-a-snapmirror-relationship,Create and initialize a SnapMirror relationship>>.
* <<show-nfs-server-configuration,Show NFS server configuration>>.
* <<create-an-export-policy-rule,Create an export policy rule>>.

REST API documentation is available by accessing the System Manager link for the system:

`https://[clus_mgmt_ip]/docs/api`

If you prefer to use Ansible playbooks, you can generate sample YAML files in System Manager via the "Save to Ansible playbook" button, found on some System Manager functions.

[[generate-an-auth_token]]
=== Generate an AUTH_TOKEN

Auth tokens authenticate a user to the ONTAP cluster when using the REST API. This token is required to run the curl examples in <<create-flexgroup-volume>>, <<delete-volumes>>, <<data-interfaces>>, and the other sections that follow. The token is a Base64-encoded string of `username:password`. Substitute the password provided by the account team for `<password>`.

==== Generate an AUTH_TOKEN using the CLI (Linux)

. Open a terminal.
. Run the following command, replacing `<password>` with the account password:
+
[source,console]
----
echo -n admin:<password> | base64
----
. Copy the Base64 output. Use that value as `[INSERT AUTH_TOKEN]` in the curl examples in <<create-flexgroup-volume>> and the following sections.

==== Generate an AUTH_TOKEN using the CLI (Windows)

. Open PowerShell.
. Run the following command, replacing `<password>` with the account password:
+
[source,powershell]
----
[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("admin:<password>"))
----
. Copy the Base64 output. Use that value as `[INSERT AUTH_TOKEN]` in the curl examples in <<create-flexgroup-volume>> and the following sections.

==== Generate an AUTH_TOKEN from the REST API documentation UI

Another way to retrieve the cluster's AUTH_TOKEN for the desired user is to use the REST API documentation located at `https://[clus_mgmt_ip]/docs/api`.

. Open the REST API documentation page.
. Scroll down to find the *Login* button.
. Click the button, log in with the desired username and password, and click *Authorize*.
. Scroll down to *GET cluster*. Expand the operation and click *Try it out*, then *Execute*.
. The curl output will contain the AUTH_TOKEN.

[[create-flexgroup-volume]]
=== Create FlexGroup volume


[source,console]
----
curl -k -X POST
"https://[CLUS_MGMT_IP]/api/storage/volumes?return_timeout=0&return_records=false" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT AUTH_TOKEN]" \
-H  "Content-Type: application/json" \
-d "{  \"constituent_count\": 64,  \"guarantee\": {    \"type\": \"none\"  },  \"name\": \"vol1\",  \"nas\": {    \"export_policy\": {      \"name\": \"default\"    },    \"junction_parent\": {      \"name\": \"vs1_root\"    },    \"path\": \"/vol1\",    \"security_style\": \"unix\",    \"unix_permissions\": 777  },  \"size\": 500000000000000,  \"snapshot_policy\": {    \"name\": \"none\"  },  \"space\": {    \"large_size_enabled\": true    },  \"style\": \"flexgroup\",  \"svm\": {    \"name\": \"svm1\"  },  \"type\": \"rw\"}"
----


*Note:* For a script to perform this task, see xref:scripts.adoc#volume-creation-and-deletion-scripts[Volume creation and deletion scripts].


[[delete-volumes]]
=== Delete volumes

First, retrieve the volume UUID that you want to delete:

[source,console]
----
curl -k -X GET
"https://[CLUS_MGMT_IP]/api/storage/volumes?is_constituent=false&fields=uuid,&return_records=true&return_timeout=15" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT_AUTH_TOKEN]"
----

Then, delete the volume (force=true means bypass the recovery queue):

[source,console]
----
curl -k -X DELETE "https://[CLUS_MGMT_IP]/api/storage/volumes/[UUID here]?force=true&return_timeout=0" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT_AUTH_TOKEN]"
----


[[display-the-storage-availability-zone-information]]
=== Display the storage availability zone information


[source,console]
----
curl -k -X GET "https://[CLUS_MGMT_IP]/api/storage/availability-zones? \fields=*&max_records=100&return_records=true&return_timeout=15" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT AUTH_TOKEN]"
----


[[data-interfaces]]
=== Data interfaces

To list all data interfaces:

[source,console]
----
curl -k -X GET "https://[CLUS_MGMT_IP]/api/network/ip/interfaces?fields=ip.address,location.node.name,location.port.name&service_policy=default-data-files&return_records=true&return_timeout=15" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT_AUTH_TOKEN]"
----

To create a data interface:

[source,console]
----
curl -k -X POST
"https://[CLUS_MGMT_IP]/api/network/ip/interfaces?return_timeout=0&return_records=false" \
-H "accept: application/json" \
-H "authorization: Basic [INSERT_AUTH_TOKEN]" \
-H "Content-Type: application/json" \
-d { \"name\": \"{LIF_NAME}\", \"scope\": \"svm\", \"svm\": \"{SVM_NAME}\", \"ip\": {  \"address\": \"{IP}\",  \"netmask\": \"{NETMASK}\" }, \"location\": {  \"home_node\": \"{NODE}\",   \"home_port\": \"{PORT}\" }
----


*Note:* For a script to create interfaces, see xref:scripts.adoc#lif-creation-and-cleanup-scripts[LIF creation and cleanup scripts].

To delete a data interface (UUID from list required):

[source,console]
----
curl -k -X DELETE "https://[CLUS_MGMT_IP]/api/network/ip/interfaces/[UUID]" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT_AUTH_TOKEN"
----


[[create-and-initialize-a-snapmirror-relationship]]
=== Create and initialize a SnapMirror relationship

Create a SnapMirror relationship (destination SVM and volume must already exist, and the SVMs must be peered):

[source,console]
----
curl -k -X POST
"https://[CLUS_MGMT_IP]/api/snapmirror/relationships?return_timeout=0&return_records=true" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT AUTH_TOKEN]" \
-H  "Content-Type: application/json" \
-d "{  \"source\": {    \"path\": \"svm1:vol1\"  },  \"destination\": {    \"path\": \"svm1:vol1_dst\"  }}"
----

Retrieve the relationship UUID:

[source,console]
----
curl -k -X GET
"https://[CLUS_MGMT_IP]/api/snapmirror/relationships?fields=uuid,source.path,destination.path,state&return_records=true&return_timeout=15" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT_AUTH_TOKEN]"
----

Initialize the SnapMirror relationship (starts the baseline transfer):

[source,console]
----
curl -k -X POST
"https://[CLUS_MGMT_IP]/api/snapmirror/relationships/[UUID]/transfers?return_timeout=0" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT AUTH_TOKEN]" \
-H  "Content-Type: application/json" \
-d "{}"
----


[[show-nfs-server-configuration]]
=== Show NFS server configuration


[source,console]
----
curl -k -X GET "https://[CLUS_MGMT_IP]/api/protocols/nfs/services?fields=*&max_records=100&return_records=true&return_timeout=15" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT AUTH_TOKEN]"
----


[[create-an-export-policy-rule]]
=== Create an export policy rule

First, retrieve the export policy ID:

[source,console]
----
curl -k -X GET
"https://[CLUS_MGMT_IP]/api/protocols/nfs/export-policies?fields=name,id,svm.name&return_records=true&return_timeout=15" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT_AUTH_TOKEN]"
----

Then, create an export policy rule (replace `[POLICY_ID]` and `[CLIENT_IP]`):

[source,console]
----
curl -k -X POST
"https://[CLUS_MGMT_IP]/api/protocols/nfs/export-policies/[POLICY_ID]/rules?return_records=true" \
-H  "accept: application/json" \
-H  "authorization: Basic [INSERT AUTH_TOKEN]" \
-H  "Content-Type: application/json" \
-d "{  \"clients\": [    {      \"match\": \"[CLIENT_IP]\"    }  ],  \"ro_rule\": [    \"any\"  ],  \"rw_rule\": [    \"any\"  ],  \"superuser\": [    \"any\"  ],  \"anonymous_user\": \"0\",  \"chown_mode\": \"unrestricted\",  \"ntfs_unix_security\": \"ignore\"}"
----
// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:test-06-api-testing.adoc[< Previous]
>| xref:appendix-rest-api-personality-differences.adoc[Next >]
|===
// navigation-links:end
