= Appendix: Client Tuning Considerations
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book

xref:appendix.adoc[← Back to Appendix]

Client tuning guidance has moved to xref:appendix-nfs-considerations.adoc#client-tuning-considerations[NFS Considerations: Client tuning].

The compatibility links below preserve existing bookmarks. Follow each link to the consolidated guidance.

[[client-tuning-considerations]]
== Client tuning considerations

See xref:appendix-nfs-considerations.adoc#client-tuning-considerations[Client tuning considerations].

[[wsize-and-rsize]]
[[wsize-rsize-recommendation]]
[[small-window-sizes]]
[[large-window-sizes]]
[[other-considerations]]
=== Wsize and rsize

See xref:appendix-nfs-considerations.adoc#wsize-and-rsize[Wsize and rsize].

[[close-to-open-consistency-and-cache-attribute-timers]]
[[cto-recommendation]]
[[how-attribute-cache-timers-work]]
[[close-to-open-cto-consistency]]
[[no-close-to-open-nocto-consistency]]
=== Close-to-open consistency and attribute caching

See xref:appendix-nfs-considerations.adoc#close-to-open-consistency-and-cache-attribute-timers[Close-to-open consistency and attribute caching].

[[nconnect]]
[[nconnect-recommendation]]
=== Nconnect

See xref:appendix-nfs-considerations.adoc#what-is-nconnect[What is nconnect] and xref:appendix-nfs-considerations.adoc#nconnect-recommendation[Nconnect recommendation].

[[nfs-readahead]]
[[readahead-recommendation]]
[[managing-readahead-values-on-clients]]
[[viewing-readahead-values-on-clients]]
[[readahead-view-example]]
[[manually-setting-readahead]]
[[persistently-setting-readahead]]
=== NFS readahead

See xref:appendix-nfs-considerations.adoc#nfs-readahead[NFS readahead].

// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:appendix-nfs-considerations.adoc[< Previous]
>| xref:appendix-rest-api.adoc[Next >]
|===
// navigation-links:end
