= Recommended Setup and Prerequisites
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book

This section covers hardware requirements, client configurations, networking, and NFS server configuration. See xref:appendix-nfs-considerations.adoc[NFS Considerations] for protocol and client-tuning details and xref:benchmark-configuration-reference.adoc[Benchmark Configuration Reference] for copy-ready commands.


[[recommended-setup-and-prerequisites]]
== Recommended setup and prerequisites


[[setup-required]]
=== Setup required

Hardware installation and initial configuration documentation links can be found in xref:overview.adoc#documentation-requirements[Documentation requirements]. This test plan assumes that the initial setup and configuration has already been performed.

*Note:* It is recommended that the AFX system starts no earlier than ONTAP version 9.19.1RC1. That release is the first release to support >16PB Storage Availability Zones and xref:feature-fabricpool.adoc[FabricPool]. If starting on an earlier release, then a cluster reinitialization (data wipe) would be required when moving to ONTAP 9.19.1 to gain support for those features. A reinitialization script is available at: xref:scripts.adoc#netapp-afx-reinitialization-script[NetApp AFX reinitialization script] (link:https://github.com/whyistheinternetbroken/AFX[GitHub]).


[[initial-state-of-the-test-environment]]
==== Initial state of the test environment

The initial environment will depend on the number of nodes acquired for the test plan. The number of nodes available may also impact the number of tests available to the system (ie, node scaling, failover, etc).

NetApp AFX officially supports a minimum configuration of:

* Four storage nodes
** Initial setup can be a two node HA-pair to provide scale/balancing testing
** 2 more nodes added later as part of test plan steps (optional)
* Two Cisco switches (for cluster, HA & disk network)
** RCF file to be provided
* Shelf minimums:
** Fully populated shelves (24 drives each shelf)
** 1 shelf of 15.3 TB SSDs
** 2 shelves of 7.6 TB, 30.1 TB, or 60.1 TB SSDs
** No drive mixing support yet
* Recommended ONTAP version of 9.19.1 or later
* Pre-configured cluster, SVM, NFS server, protocol licenses
* Node and cluster management interfaces for access to the CLI and GUI


[[clients]]
==== Clients

For the best results, provide at least four modern NFS clients to run storage benchmarks. Client OS is not important, provided it adheres to RFC standards and are within a few minor releases of the newest versions available. All clients should have high performance specs including CPU, memory & networking, ideally 100GB+. All clients should be routable to all data interfaces in the NetApp AFX cluster -- especially if features such as pNFS and NFSv4.1 session trunking are used.

*Note:* This test plan mainly focuses on NFS, but many of the concepts can also be applied to SMB operations. Future versions of this test plan may include SMB, multiprotocol NAS, etc.

Our internal benchmark results were generated with the following client configurations:

[source,console]
----
Ubuntu 24.04.1 LTS
6.8.0-51-generic
Doca-all 3.4.0 3.4.0-085000 with rpcrdma module
----

A combined client tuning script is available at link:https://github.com/whyistheinternetbroken/Benchmarking/tree/main/Clients[Benchmarking/Clients]. For the reviewed command set and warnings used by this test plan, see xref:benchmark-configuration-reference.adoc#client-configuration-commands[Client configuration].


[[client-network-and-nic-tuning]]
===== Client network & NIC tuning

Internal benchmark clients used RX/TX rings of 8192. RDMA clients also used PFC priority 3, DSCP trust, and RoCE TOS 106. Apply these only when the end-to-end network design supports them. See xref:benchmark-configuration-reference.adoc#client-nic-commands[NIC and RDMA commands].


[[client-os-tuning]]
===== Client OS tuning

Dirty-page writeback and TCP/RDMA slot-allocation settings are consolidated in xref:benchmark-configuration-reference.adoc#client-os-commands[Client operating-system tuning]. Size dirty-page byte values for client RAM and validate changes before making them persistent.


[[networking-requirements]]
==== Networking requirements

All data network interfaces in an ONTAP SVM should be routable to all clients for best results in this test plan. The IP address count needed are as follows:

* Four (4) _intercluster_ interface IP addresses
** One per node required; to be used for xref:test-04-data-migration.adoc[SnapMirror] and xref:test-flexcache.adoc[FlexCache] operations (unless not testing these features)
* At least eight (8) data interface IP addresses (two per node)
** pNFS supports up to sixteen (16) data IP interfaces per node
** Can be TCP or RDMA capable
* One (1) cluster management interface IP address for administrative interaction
* Four (4) node management interface IP addresses (one per node)
* Four (4) service processor/BMC IP addresses (one per node)
* Client IP addresses
** NICs can be bonded, trunked, etc. No set requirements unless using RDMA, which may have support limitations for certain NIC models


[[nfs-server-configuration]]
==== NFS server configuration

Configure NFSv3 and NFSv4.1, pNFS, session trunking, 64-bit identifiers, a 1MB server transfer maximum, and the benchmark session-slot value before validation. The NFSv4 ID domain must match the clients. Use xref:benchmark-configuration-reference.adoc#ontap-nfs-server-command[the consolidated NFS server command] so setup and benchmark procedures share one source of truth.

To verify the NFSv4 ID domain on the client:

[source,console]
----
# nfsidmap -d
user-domain.company.com
# cat /etc/idmapd.conf | grep Domain
Domain = user-domain.company.com
----


*Note:* If those commands do not work, you likely have not installed the proper NFS packages to leverage NFSv4.x. For example, nfs-common for Debian/Ubuntu-based systems.


[[benchmark-cli-configuration]]
===== Benchmark CLI configuration

Use xref:benchmark-configuration-reference.adoc[Benchmark Configuration Reference] for client, mount, ONTAP, verification, and statistics commands. The automation equivalent is link:https://github.com/whyistheinternetbroken/Benchmarking/blob/main/ONTAP/NAS/configure-nfs-server.sh[configure-nfs-server.sh]. For the rationale and production caveats behind benchmark-only changes, see xref:test-07-08-performance-testing-considerations.adoc[Performance testing considerations].
// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:overview.adoc[< Previous]
>| xref:appendix-nfs-considerations.adoc[Next >]
|===
// navigation-links:end
