= Appendix: Storage Benchmark Testing
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book
:stylesheet: styles/table-styling.css
:stylesdir: .


xref:appendix.adoc[â† Back to Appendix]

Guides for SPEC SFS 2020 and DLIO/MLcommons benchmark tools including workload definitions, model runs, data generation, and NFS operation breakdowns.


[[storage-benchmark-testing]]
== Storage benchmark testing

The following section covers the specific benchmarking tool we will use for this test plan.

[[spec-sfs-2020]]
=== SPEC SFS 2020

We will be using the SPEC SFS 2020 benchmark to simulate EDA frontend, backend and blended workloads. The test profiles use the workload profiles found in the , as well as details on how to set up and configure the benchmark.

[[frontend-eda-workload-breakdown----specsfs-2020]]
==== Frontend EDA workload breakdown -- SPECSFS 2020

The following table shows the NFS operations involved in the SPECSFS 2020 benchmark.

[.light-gray-header,cols="1,1,1,1",options="header"]
|===
h| NFS operation distribution |  |  |
| Operation type | % | Operation type | %
| read | 0 | read file | 7
| mmap read | 0 | random read | 8
| write | 0 | write file | 10
| mmap write | 0 | random write | 15
| rmw | 0 | append | 0
| mkdir | 1 | rmdir | 0
| readdir | 0 | create | 2
| unlink | 1 | unlink2 | 1
| stat | 39 | access | 15
| rename | 0 | copyfile | 0
| lock | 0 | chmod | 1
| statfs | 0 | pathconf | 0
| trunc | 0 | neg_stat | 0
|===


NOTE: Due to the metadata-heavy nature of frontend EDA workloads, it is recommended to use NFSv3.


[[backend-eda-workload-breakdown]]
==== Backend EDA workload breakdown

The following table shows the NFS operations involved in the SPECSFS 2020 benchmark.

[.light-gray-header,cols="1,1,1,1",options="header"]
|===
h| NFS operation distribution |  |  |
| Operation type | % | Operation type | %
| read | 50 | read file | 0
| mmap read | 0 | random read | 0
| write | 50 | write file | 0
| mmap write | 0 | random write | 0
| rmw | 0 | append | 0
| mkdir | 0 | rmdir | 0
| readdir | 0 | create | 0
| unlink | 0 | unlink2 | 0
| stat | 0 | access | 0
| rename | 0 | copyfile | 0
| lock | 0 | chmod | 0
| statfs | 0 | pathconf | 0
| trunc | 0 | neg_stat | 0
|===


NOTE: Since backend EDA workloads are read/write heavy with very little metadata, it is worth using NFSv4.1 with pNFS and session trunking.


[[definition-of-relevant-operations-in-spec-sfs-2020]]
==== Definition of relevant operations in SPEC SFS 2020

The following section attempts to define the operations mentioned in the frontend and backend workload sections above.

[.light-gray-header,cols="1,1",options="header"]
|===
h| Operation type | What it does
| read | Sequential reads to an already open file.
| read file | Open, read, close file. End-to-end read.
| mmap read | Memory map read.
| random read | Random read.
| write | Sequential write to an already open file.
| write file | Open, write, close. End-to-end write.
| mmap write | Memory map write.
| rmw | Read/modify/write.
| append | Add data to end of existing file.
| mkdir | Make directory.
| rmdir | Remove directory.
| readdir | List contents of directory. (Includes readdir+ operations)
| create | Create file metadata operation; checks if file exists, allocates a new inode.
| unlink | Deletes a file.
| unlink2 | 2nd unlink on a different file.
| stat | Retrieves the attributes of a file or directory, such as size, permissions, owner, and timestamps. (ie, du and ls)
| access | Checks the access permissions for a file or directory to determine if the client has the necessary permissions (read, write, execute).
| rename | Rename a file or folder.
| copyfile | Copies a file from one to another.
| lock | Locks a file.
| chmod | Change the permissions of a file or folder.
| statfs | Retrieve information about the overall file system. (ie, df)
| pathconf | Retrieves configuration information about a file or directory, such as maximum filename length, maximum path length, and other file system limits.
| trunc | Truncates a file to a specified length. This can either shorten or extend the file, with the extended portion being filled with zeros.
| neg_stat | Refers to a negative status response indicating that a file or directory does not exist or an operation failed. This is not a standard NFS operation but rather a status code.
|===


[[dliomlcommons]]
=== DLIO/MLcommons

We will be using the MLcommons benchmark leveraging DLIO.
For installation/configuration, see here:
https://github.com/mlcommons/storage

NOTE: It is recommended to use Ubuntu 22 (latest version), but RHEL 9.x is also a possible version to use for clients.


NOTE: MLcommons updates fairly regularly. Their updates may outpace what is in this document. Use their site as a single source of truth.


[[about-mlcommons]]
==== About MLcommons

MLcommons is a nascent benchmark for AI/ML workloads that is currently in version 2.0 (as of May 2025). While it is not yet the standard benchmark for these types of workloads, it is one of the frontrunners to be akin to SPEC SFS benchmarking.
The MLcommons benchmark tool covers several areas of the AI/ML workflow, including:
* VectorDB search
* Checkpointing
* Training/inference
MLcommons attempts to simulate the end-to-end workflow by building in the time it would take to run specific AI/Ml jobs on GPUs, which reduces the overall cost to test AI/ML workloads. GPU times are standardized and offer options such as the  and  Tensor Core GPUs.
From  page:
MLPerf Storage emulates accelerators for the training workloads with the tool DLIO developed by Argonne National Labs. DLIO uses the standard AI frameworks (PyTorch, Tensorflow, Numpy, etc) to load data from storage to memory at the same intensity as a given accelerator.
*This emulation means that submitters do not need to use hardware accelerators (e.g., GPUs, TPUs, and other ASICs) when running MLPerf Storage - Training.*
Instead, our benchmark tool replaces the training on the accelerator for a single batch of data with a sleep() call. The sleep() interval depends on the batch size and accelerator type and has been determined through measurement on a system running the real training workload. The rest of the data ingestion pipeline (data loading, caching, checkpointing) is unchanged and runs in the same way as when the actual training is performed.
There are two main advantages to accelerator emulation. First, MLPerf Storage allows testing different storage systems with different types of accelerators. To change the type of accelerator that the benchmark emulates (e.g., to switch to a system with NVIDIA H100 GPUs instead of A100 GPUs), it is enough to adjust the batch size and sleep() parameter. The second advantage is that MLPerf Storage can put a high load on the storage system simply by increasing the number of emulated accelerators. This allows for testing the behavior of the storage system in large-scale scenarios without purchasing/renting the AI compute infrastructure.

[[about-vectordb-search-in-mlcommons-benchmark]]
===== About vectorDB search in MLcommons benchmark

The VectorDB benchmark is designed to measure the performance and efficiency of vector databases, which are specialized systems optimized for storing, indexing, and querying high-dimensional vectors. These vectors are commonly used in machine learning applications such as recommendation systems, image retrieval, and natural language processing (NLP). This type of workload is generally comprised of random reads and writes to storage systems.
MLcommons provides _datagen_ and _run-search_ options to perform this benchmark. The datagen portion will create a simulated dataset, while run-search will perform the vectorDB search benchmark test.

NOTE: Because of how new vectorDB testing is for this benchmark suite (new as of v2.0), this EAP will not cover vectorDB search benchmarks.


[[about-checkpointing-in-mlcommons-benchmark]]
===== About checkpointing in MLcommons benchmark

Checkpointing in AI/ML workloads is used to reduce the impact of progress lost in the event of a training job failure. Checkpointing workloads have an IO profile of:
* Sequential writes for saving checkpointing information
* Random reads for restoring from checkpoints
* Metadata operations (mostly SETATTR)

NOTE: Because of how new checkpoint testing is for this benchmark suite (new as of v2.0), this EAP will not cover checkpointing benchmarks


[[about-training-in-mlcommons-benchmark]]
===== About training in MLcommons benchmark

The training benchmark in MLcommons was the original benchmark released and will be the focus for this EAP. AI/ML training is a heavily sequential read workload on a static dataset and requires high throughput for this type of workload. In MLcommons, the following workload types are used.
* Image segmentation using the  model
* Image classification using the  model
* Cosmology parameter prediction using the  model

[[generating-datasizes]]
===== Generating datasizes

The size of the training dataset is determined with the mlpstorage datasize command and is dependent on the number accelerators defined. Examples below.
*U-Net3D*

[source,console]
----
# mlpstorage training datasize -m unet3d  --client-host-memory-in-gb 64 --max-accelerators 4 --num-client-hosts 2 --accelerator-type a100
Setting attr from max_accelerators to 4
2025-05-21 13:54:48|STATUS: Benchmark results directory: /tmp/mlperf_storage_results/training/unet3d/datasize/20250521_135448
2025-05-21 13:54:48|STATUS: Instantiated the Training Benchmark...
2025-05-21 13:54:48|RESULT: Minimum file count dictated by 500 step requirement of given accelerator count and batch size.
2025-05-21 13:54:48|RESULT: Number of training files: 14000
2025-05-21 13:54:48|RESULT: Number of training subfolders: 0
2025-05-21 13:54:48|RESULT: Total disk space required for training: 1911.45 GB
----

*Resnet50*

[source,console]
----
# mlpstorage training datasize -m resnet50 --client-host-memory-in-gb 64 --max-accelerators 4 --num-client-hosts 2 --accelerator-type a100
Setting attr from max_accelerators to 4
2025-05-21 14:06:18|STATUS: Benchmark results directory: /tmp/mlperf_storage_results/training/resnet50/datasize/20250521_140618
2025-05-21 14:06:18|STATUS: Instantiated the Training Benchmark...
2025-05-21 14:06:18|RESULT: Minimum file count dictated by dataset size to memory size ratio.
2025-05-21 14:06:18|RESULT: Number of training files: 4790
2025-05-21 14:06:18|RESULT: Number of training subfolders: 0
2025-05-21 14:06:18|RESULT: Total disk space required for training: 639.89 GB
----

*Cosmoflow*

[source,console]
----
# mlpstorage training datasize -m cosmoflow --client-host-memory-in-gb 64 --max-accelerators 4 --num-client-hosts 2 --accelerator-type a100
Setting attr from max_accelerators to 4
2025-05-21 14:09:25|STATUS: Benchmark results directory: /tmp/mlperf_storage_results/training/cosmoflow/datasize/20250521_140925
2025-05-21 14:09:25|STATUS: Instantiated the Training Benchmark...
2025-05-21 14:09:25|RESULT: Minimum file count dictated by dataset size to memory size ratio.
2025-05-21 14:09:25|RESULT: Number of training files: 242954
2025-05-21 14:09:25|RESULT: Number of training subfolders: 0
2025-05-21 14:09:25|RESULT: Total disk space required for training: 640.00 GB
----


[[about-u-net3d]]
===== About U-Net3D

The U-Net3D model simulates image segmentation (such as 3D medical imaging). When generating a dataset, the default average file size is 146,600,628 bytes (146MB) and is defined in the unet3d_GPU.yaml file.

[[about-resnet50]]
===== About Resnet50

The Resnet50 model is a neural network used in image classification, object detection, semantic segmentation and other computer vision tasks. The default average file size for Resnet50 is 114,660 bytes (~112KB) and is defined in the resnet50_GPU.yaml file.

[[about-cosmoflow]]
===== About Cosmoflow

Cosmoflow is a deep learning model that attempts to model the universe and predict matter and dark energy density and other cosmological applications. The default average file size for Cosmoflow datasets is 2,828,486 bytes (~2.8MB) and is defined in the _cosmoflow_GPU.yaml_ file.

[[nfs-operation-breakdown-for-model-runs]]
===== NFS operation breakdown for model runs

The following table shows a breakdown of the NFS operations seen during a training run of each model. The point of this table is to help make decisions about how to best configure storage and clients for these benchmark runs.
These were generated using default NFS mount options and a 1MB rsize.

[.light-gray-header,cols="1,1,1,1",options="header"]
|===
h|  | U-Net3D | Resnet50 | Cosmoflow
| Number of files trained | 12000 | 2395 | 242954
| ACCESS | <1% |  | 5%
| CLOSE | <1% |  | 5%
| COMPOUND | 90% | 98% | 31%
| CREATE | <1% |  |
| GETATTR | <1% |  | 8%
| GETDEVICEINFO (pNFS) | <1% |  |
| OPEN | <1% |  | 5%
| PUTFH | 4% | <1% | 25%
| READ | 89% | 98% | 17%
| SEQUENCE | 4% | <1% | 25%
|===


[[read-size-histogram]]
===== READ size histogram

The following table shows the incoming block sizes observed for each training workload test on a 1MB mount using default mount options.

[.light-gray-header,cols="1,1,1,1",options="header"]
|===
h|  | U-Net3D | Resnet50 | Cosmoflow
| Number of files trained | 12000 | 2395 | 242954
| Average file size | ~140MB | ~136MB | ~2.7MB
| <= 512B | 1636 |  |
| <= 1KB | 1794 | - | 4
| <= 2KB | 3478 | - | 12
| <= 4KB | 951114 | 147209 | 18581
| <= 8KB | 5915 | 8813 | 1889
| <= 32KB | 687 | - |
| <= 64KB | 1428 | 13 | -
| <= 128KB | 2915 | 6506810 | -
| <= 256KB | 7151 | 3259423 | -
| <= 512KB | 14997 | - | 20
| <= 1MB | 8270819 | - | 3643426
|===
// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:appendix-rest-api.adoc[< Previous]
>| xref:appendix-statistics-counters.adoc[Next >]
|===
// navigation-links:end
