= Datasets, Workloads, and ONTAP Limits
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book
:stylesheet: styles/table-styling.css
:stylesdir: .

This section covers supported workload types, data protocols, NAS protocol features, volume recommendations, S3 features, and ONTAP limits that affect testing.


[[datasets-and-workloads]]
== Datasets and workloads

NetApp AFX is intended for high performance NAS and object workloads. Key attributes include:

* Massive throughput and IOPS
* Independent scaling of storage nodes and capacity
* Flexible workload support on shared datasets with minimal tuning changes

Because it runs ONTAP, NetApp AFX can support multiple workload classes at the same time. Common industries include:

* Media and entertainment (movies, television, streaming, music, gaming)
* Electronic Design Automation/EDA (semiconductor and chip development)
* Oil, gas & seismic
* Financials (high volume trading, prediction, AI/ML)
* Healthcare (medical imaging, AI/ML, LLM)
* Software development

[[workload-use-cases]]
=== Workload use cases

Datasets and testing of workloads will be dependent on the overall goal of the test plan, but there are three main scenarios in play here.

[[workload-types]]
==== Workload types

NetApp AFX, while initially designed for AI/ML training and inference use cases, is capable of hosting a variety of different workloads including:

* High throughput read/write (random or sequential)
* High IOP workloads (small, random IO/high metadata)

From an application/solution perspective, relevant workloads include:

* AI/ML training and inference
* Software development
* HPC
* Virtualization
* Media and entertainment

[[if-you-are-currently-using-ontap]]
==== If you are currently using ONTAP

If ONTAP is currently running your production workloads, this test plan will use SnapMirror to efficiently and quickly replicate volumes to NetApp AFX.
Some considerations:
* SnapMirror *_from_* unified ONTAP to NetApp AFX can be performed with any unified ONTAP version within 2 major releases (ie, ONTAP 9.16.1 -> 9.18.1).
* SnapMirror *_to_* unified ONTAP from NetApp AFX is only supported on unified ONTAP running ONTAP 9.16.1 when replicating FlexGroup volumes. FlexVol volumes can still use the 2 version compatibility rule.
* Alternatively, it is also possible to copy subsets of data using NAS protocol-based tools such as XCP, robocopy, etc. Those methods will not be covered in the scope of this document.

[[if-you-are-not-currently-using-ontap]]
==== If you are not currently using ONTAP

If ONTAP is not currently being used within your environment, then a NAS protocol-level copy of datasets to NetApp AFX or initial data generation (ie, via storage benchmarking tools) will be needed to run portions of this test plan. Those methods will not be covered in the scope of this document.
An alternative method of leveraging industry standard benchmarks for the workload are provided as an optional test plan in this document.

[[supported-data-protocols]]
=== Supported data protocols

NetApp AFX is compatible with the following data protocols:

* *NFS*
** NFSv3
** NFSv4.0
** NFSv4.1 / NFSv4.2 (with pNFS)
** NFS over RDMA
* *SMB*
** SMB2.x
** SMB3.x
** Dual protocol NAS (SMB and NFS)
* *Object*
** S3
** File / object multiprotocol (present an existing NAS volume as an S3 bucket)

*Note:* As mentioned previously, this test plan currently focuses mainly on NFS and object workloads. Future versions of this test plan may include SMB, dual protocol, etc.


[[recommended-nas-protocol-features]]
=== Recommended NAS protocol features

Most modern clients have support for specific NFS features that workloads running on NetApp AFX systems can leverage and benefit from.

*Note:* When using NFSv4.x, use only NFSv4.1 and later.


* *Nconnect*
** *Purpose:* Multiple TCP connections per single mount point for increased performance and scale.
** *NFSv3:* Yes
** *NFSv4.1+:* Yes
** *Compatibility notes:*
*** Nconnect + pNFS = OK
*** Nconnect + session trunking = OK
*** Nconnect + session trunking + pNFS = not recommended
* *Trunking*
** *Purpose:* Combines multiple interfaces into one connection to provide increased throughput and resiliency. (Not to be used with nconnect)
** *NFSv3:* No
** *NFSv4.1+:* Yes
* *pNFS*
** *Purpose:* Data locality for improved latency and parallel access to single file portions of large files for better performance when using FlexGroup volumes.
** *NFSv3:* No
** *NFSv4.1+:* Yes


[[volume-type-recommendation]]
=== Volume type recommendation

It is highly recommended to leverage FlexGroup volumes in this test plan due to their ability to spread a working dataset across multiple nodes and CPU threads for higher performance.
To create a FlexGroup volume in the AFX command line:

[source,console]
----
::> volume create -volume flexgroup -size 500t -vserver svm1 -auto-provision-as flexgroup
----

Volume creation automation scripts are available at:
link:https://github.com/whyistheinternetbroken/Benchmarking/tree/main/ONTAP/volumes[Benchmarking/ONTAP/volumes]

To create a FlexGroup volume in System Manager:

* Navigate to Storage → Volumes
* Click +Add
* Select "High throughput" to create a FlexGroup

To leverage REST API, see:
link:https://docs.netapp.com/us-en/ontap-afx/rest/api-reference.html[REST API Reference]

[[s3-specific-features]]
=== S3 specific features

ONTAP S3 supports a limited number of S3 features and functionality. Support for these features spans both NetApp AFX and Unified ONTAP.
For details and recommendations, see:
link:https://docs.netapp.com/us-en/ontap/s3-config/index.html[Learn about S3 configuration]

[[ontap-limits-considerations]]
=== ONTAP limits considerations

NetApp AFX runs ONTAP, and because of that, you need to be aware of what file system limits are present in ONTAP, since testing/benchmarking can run into errors if these limits are reached.
The following table spells out specific limits and what their impact may be on testing. The test plans attempt to build most of these into the tests to avoid unforeseen issues. For more information, see the Performance testing configuration section.

* *Maximum volume size*
** *Value:*
*** 100TB (`-is-large-size-enabled false`)
*** 300TB (`-is-large-size-enabled true`)
*** ONTAP sets this option to false by default. This option also impacts the maximum FlexGroup size (20PB vs. 60PB).
** *Potential impact:* If a volume reaches its maximum allowed size and then fills to 100%, there is no way to expand it beyond that. Testing would fail due to lack of space.
** *Remediation:*
*** Set `-is-large-size-enabled true` at volume creation.
*** Configure volume autosize.
*** Configure monitoring and alerts for volumes approaching 90% capacity used.
*** Delete snapshots or data if the limit is reached.
* *Maximum file size*
** *Value:*
*** 16TB (`-is-large-size-enabled false`)
*** 127TB (`-is-large-size-enabled true`)
*** ONTAP sets this option to false by default.
** *Potential impact:* Reaching the maximum file size limit will show an "out of space" error and the file will no longer be writeable. In some cases, if the space error occurs during an in-flight write, that write may be corrupted.
** *Remediation:*
*** Set `-is-large-size-enabled true` at volume creation.
*** Avoid creating files larger than the allowed maximum size.
* *Maximum files/inodes*
** *Value:*
*** 2 billion (FlexVol)
*** 200 billion (FlexGroup)
*** The maximum files/inodes allowed in a single volume is determined by the `-files` volume option.
** *Potential impact:* If a test attempts to exceed the maximum files allowed, the test will fail due to an "out of space" error (`callhome.no.inodes` in ONTAP).
*** This error is a common root cause for test failures, as the max file value is variable based on volume size and the absolute maximums are only reached when the volume size (FlexVol or constituent FlexGroup volume) is ~7.8TB.
*** By default, the maximum files value is determined by volume size (one inode per 4K of space) and does *not* allow the absolute maximum number of files. For instance, if a volume size is 100GB, then the default value is 3,112,959, but the maximum allowed would be 24,903,679.
** *Remediation/prevention:*
*** Create volumes at a large enough size to support the maximum files allowed (>7.8TB for FlexVol, `7.8 * 10 * nodes` for FlexGroup).
*** Set `-files-set-maximum true` at volume creation.
*** Monitor inode allocation for the volume.
*** Consider setting quotas on the volume to alert when an inode allocation value has been reached.
*** Delete files if the limit is reached.
* *Maximum files per directory (maxdirsize)*
** *Value:*
*** 320MB (default)
*** The number of files is variable depending on several factors, but is generally in the ~2-4 million range for FlexVol volumes and ~1-2.5 million for FlexGroup volumes.
** *Potential impact:* If a directory reaches its maximum directory size allowed in ONTAP, clients will see an "out of space" error. ONTAP will show `wafl.dir.size.max` or `wafl.dir.size.max.warning` in EMS (`event log show` in CLI).
*** It is a best practice to keep the file counts in single directories lower than the maximums allowed by default.
*** 320MB is the size allocated to memory for a directory index file. Each time a file is added to a directory, the index file increases in size. This size is impacted by file count, file name length, hardlinks, and character types.
*** It is generally not recommended to increase `maxdirsize`, as it can impact overall system performance for all workloads when approaching the higher end of the limits. However, in benchmark tests, this limit can be modified to verify observed impacts.
** *Remediation/prevention:*
*** Avoid creating millions of files in a single directory when possible.
*** Monitor for maxdirsize usage via EMS messages `wafl.dir.size.warning` and `wafl.dir.size.max.warning`.
*** Increase `-maxdirsize` to no more than 4GB if testing includes creating >2 million files in a single directory.
* *TCP connections*
** *Value:* 100,000 per node
** *Potential impact:* If a TCP connection maximum is exceeded on a node, new mounts will be disallowed until connections are freed. This is uncommon due to the high connection limit, but in Kubernetes/container environments where NFS is used, this can happen when initial mounts occur across many clients, TCP is not specified in mount options, and nconnect is in use. This mainly impacts NFSv3.
** *Remediation/prevention:*
*** Use the `tcp` mount option to avoid UDP mount requests for NFSv3.
*** If using nconnect, total mount connections allowed become `100,000 / nconnect value`.
*** Use DNS load balancing or another round-robin mechanism to balance mounts across nodes in the cluster.
* *NFSv4.x session slots*
** *Value:* 2000 (180 default)
** *Potential impact:* Too high or low of a value can negatively impact performance in ways that are hard to track down. Too low can create NFS flow control; too high may impact CPU utilization.
*** For details, see: https://learn.microsoft.com/en-us/azure/azure-netapp-files/performance-linux-concurrency-session-slots
*** Session slots are the number of supported in-flight requests in a single NFSv4.x session.
*** By default, ONTAP supports 180 session slots, but in-house performance testing has shown lowering this value to 64 is often optimal.
** *Remediation/prevention:*
*** Limit session slots (`-v4.x-session-num-slots`) to 64 when using NFSv4.x.
* *RPC slot tables*
** *Value:* 128 per TCP connection
** *Potential impact:* NFS slot tables control mount operation concurrency. If exceeded in ONTAP, the NFS server creates a wait queue for incoming operations, impacting performance.
*** One main sign is EMS message `nblade.execsOverLimit`.
*** By default, modern NFS clients allow dynamic control of slot tables via client/server communication. ONTAP's NFS server has no configurable/advertised slot-table value, so clients can send up to 65536 entries to a mount IP, greatly exceeding ONTAP's 128 maximum.
*** This can impact both NFSv3 and NFSv4.x.
** *Remediation/prevention:*
*** Modify `sunrpc` slot tables on NFS clients to no more than 128 (preferably 64) for NFSv3.
*** Modify the session slot value for NFSv4.x on the ONTAP NFS server.
*** Monitor for `nblade.execsOverLimit`.
// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:setup.adoc[< Previous]
>| xref:test-plans.adoc[Next >]
|===
// navigation-links:end
