= Optional Feature: Global Deduplication
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book

xref:test-plans.adoc[â† Back to Test Plans]

Global deduplication is new in ONTAP 9.19.1 and deduplicates data across all nodes using a single shared filesystem namespace.


[[global-deduplication]]
== Global deduplication

Prior to ONTAP 9.19.1, AFX deduplication occurred at the node level, where only data in volumes owned by a specific node was eligible for deduplication. In Unified ONTAP, that deduplication domain was at the aggregate level (via cross-volume deduplication). As a result, if you had files on volumes owned by node1 that were identical in volumes owned by its HA partner (node2), then you did not gain efficiency benefits.
Because NetApp AFX provides a single capacity pool for all nodes, it leverages a single filesystem namespace for volumes. This means that with the new global deduplication feature, all volumes across all nodes can share the same filesystem space and duplicate files and blocks are located in the same deduplication domain.

[[operation]]
=== Operation

Global deduplication is not an inline process, but instead runs post-process across the capacity pool. The jobs are opportunistic and will defer to production workload performance to mitigate the effects of deduplication.

[[configuration]]
=== Configuration

Global deduplication is on by default in NetApp AFX.
To show if it is enabled:

[source,console]
----
AFX::*> global-dedupe show
(storage aggregate efficiency global-dedupe show)
Aggregate          State
------------------ ----------
storage_availability_zone_0
Enabled
----


NOTE: NetApp AFX doesn't use the concept of physical aggregates, but the storage efficiency commands do run under the storage aggregate command family for backwards compatibility.

Global deduplication can be disabled with the "stop" command, but it is not recommended to modify it in general. For the purposes of these tests, we will disable global dedupe to illustrate what impact it can have on performance and space savings. However, the current ONTAP release can only re-enable it via diag privilege commands (a bug has been opened to correct that and should be fixed in a future release.
To re-enable global deduplication:

[source,console]
----
AFX::> set diag
AFX::*> run local flexaggr global_dedup enable -all
----


NOTE: This process can take a few minutes to complete. 

You can check the current status with:

[source,console]
----
AFX::> set diag
AFX::*> run local flexaggr global_dedup status
AFX::*> global-dedupe show
----

The status will show "disabled" or "unknown" for a period but will eventually enter the "Enabled" state.

[[test-plan----global-deduplication]]
=== Test plan -- Global deduplication

This test attempts to show the following.
* How global deduplication impacts performance
* The space savings realized with global deduplication vs. traditional node and volume based
* How to view statistics for global deduplication operations
The test plan uses the benchmarking utility called  to generate load and to create a dataset that can be deduplicated. This test plan can be performed in conjunction with the dynamic storage efficiency test plan seen later in this document.
You can access the test plan here:
// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:test-ndu.adoc[< Previous]
>| xref:feature-dynamic-storage-efficiency.adoc[Next >]
|===
// navigation-links:end