= Performance Test Plan: Basic Functionality Tests
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book

This section covers core performance tests (Tests 1-12), NFS export policy, volume configuration, mount options, client and network configuration, and ONTAP feature settings. For NFS server configuration reference, see xref:setup.adoc[Setup].


[[basic-functionality-tests]]
== Basic functionality tests

The goals of these tests are to illustrate the basic administrative and functionality of NetApp AFX in contrast to other storage platforms you may be used to (or to unified ONTAP itself). These tests build as they proceed, so it is important not to skip these tests to ensure later tests work as expected.

[[validate-the-cluster-setup]]
=== Validate the cluster setup

The first test plan here is to validate the cluster heath, configuration, etc.

.Test ) Validate the cluster setup.


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 1 | Tester: |  | Date: | 
| Test requirements: | No specific requirements |  |  | 
| Test procedure – GUI: +
Log into the System Manager GUI via https://[clus_mgmt_IP] +
The system dashboard will show errors, warnings, capacity information, and a high-level overview of the storage hardware. +
 +
Click on “Errors” to view any issues the cluster may be having. This will take you to Events & Jobs -> Events. +
 +
Click on System Alerts to see specific alerts.  +
 +
Under Cluster -> Overview, you can see the following via the tabs on the page: +
Node health and information +
Shelves +
Shelf IO modules +
Disks +
Switches +
Cabling +
Scroll through each of these and take note of the different components in the NetApp AFX architecture. +
 +
Note: You can toggle between list view and graphical view on each tab. +
 +
The cabling diagram provides a clean view of the clusters physical layout.  +
 +
Use the down arrows  in each of the Nodes, Switches and Disk Shelves to see their associated ports. Some ports will be unused. To see a consolidate cabling diagram with only the used ports, uncheck “Show unused ports.” +
 +
Test procedure – CLI: +
Log in to the NetApp AFX CLI +
Verify cluster health. +
AFX::*> set advanced +
AFX::*> cluster show +
AFX::*> system health status show +
AFX::*> system health subsystem show +
AFX::*> health alert show +
 +
Ping cluster interfaces to ensure health and connectivity. +
AFX::*> cluster ping-cluster -node AFX-01 +
Host is AFX-01 +
Getting addresses from network interface table... +
Cluster AFX-01_clus1 192.168.76.221 AFX-01 e7a +
Cluster AFX-01_clus2 192.168.76.228 AFX-01 e7b +
Cluster AFX-02_clus1 192.168.76.224 AFX-02 e7a +
Cluster AFX-02_clus2 192.168.76.231 AFX-02 e7b +
Local = 192.168.76.221 192.168.76.228 +
Remote = 192.168.76.224 192.168.76.231 +
Cluster Vserver Id = 4294967293 +
Ping status: +
.... +
Basic connectivity succeeds on 4 path(s) +
Basic connectivity fails on 0 path(s) +
................ +
Detected 9000 byte MTU on 4 path(s): +
    Local 192.168.76.221 to Remote 192.168.76.224 +
    Local 192.168.76.221 to Remote 192.168.76.231 +
    Local 192.168.76.228 to Remote 192.168.76.224 +
    Local 192.168.76.228 to Remote 192.168.76.231 +
Larger than PMTU communication succeeds on 4 path(s) +
RPC status: +
2 paths up, 0 paths down (tcp check) +
2 paths up, 0 paths down (udp check) +
 +
Show that disk shelves are connected and available. +
AFX::*> storage shelf show +
AFX::*> storage shelf port show +
 +
Verify the system HA status. +
AFX::*> system ha interconnect status show +
AFX::*> system ha interconnect port show +
AFX::*> storage failover show +
 +
Verify the storage switches are connected and available. +
AFX::*> system switch ethernet show +
 +
Show network interfaces. +
AFX::*> network interface show +
 +
Show the storage availability zone. +
AFX::*> storage availability-zone show +
 +
Show system processor interfaces. +
AFX::*> service-processor show +
 +
Show available cluster space. +
AFX::*> cluster space show +
 +
Verify the NFS server is configured properly. +
AFX::*> nfs show -fields v4.1,v4-id-domain,v4.1-pnfs,v4.1-trunking,tcp-max-xfer-size,v3,v3-64bit-identifiers,v4-64bit-identifiers,v3,v4.1-read-delegation,v4.1-write-delegation,rdma +
 +
The NFS server output should show: |  |  |  | 
| Expected outcome(s): +
The cluster is healthy and available. +
The shelves are cabled properly. +
The network interfaces are present for management Ips. +
Storage availability zone concepts are reviewed. +
Cabling diagrams are viewed. +
Error states are not present. If errors are present, resolve with support before moving on to the next sections. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[enable-autosupport-optional]]
=== Enable AutoSupport (optional)

AutoSupport is enabled for these environments to ensure the following:
* Proper call home / case creation when needed.
* Data collection for the AFX clusters, including detailed log files.
* Troubleshooting/support
AutoSupport requires the ONTAP system to be able to access the internet to send its payload to NetApp. For environments that do not allow external access please follow this procedure to manually upload an AutoSupport.  
For more information on what AutoSupport is, the information that AutoSupport contains, or how to configure AutoSupport, please consult . 

.Test ) Enable AutoSupport


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 2 | Tester: |  | Date: | 
| Test requirements: | No specific requirements |  |  | 
| Test procedure: +
Log into the System Manager GUI via https://[clus_mgmt_IP] +
Navigate to Cluster -> Settings. +
Under AutoSupport, if not already enabled, click the menu and select enable. +
 +
Test AutoSupport connectivity |  |  |  | 
| Expected outcome(s): +
AutoSupport is enabled. +
A test ASUP succeeds. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[create-network-interfaces]]
=== Create network interfaces

ONTAP can be configured with multiple network interfaces for management, data access and inter-cluster connectivity. 

.Test ) Create network interfaces.


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 3 | Tester: |  | Date: | 
| Test requirements: | No specific requirements |  |  | 
| Test procedure: +
Log into the System Manager GUI via https://[clus_mgmt_IP] +
Navigate to Network -> Overview. +
Click the “+ Add” button under Network interfaces. +
 +
Select “data” for the interface type and select the desired options, specify a name, home node, etc. +
 +
Repeat the above step for each node. Create at least 2 data interfaces per node to provide paths for NFS session trunking. +
Alternately, use the LIF creation script found in the Appendix of this document. |  |  |  | 
| Expected outcome(s): +
Two or more data interfaces are created per node. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[data-migration-optional]]
=== Data migration (optional)

The goal for this test is to provide a mechanism to display the ease and speed of migration of data from unified ONTAP to NetApp AFX using NetApp SnapMirror technology. This test is optional if you plan on generating your own datasets on the cluster.
Additionally, we can also show how NetApp AFX can replicate to a unified ONTAP system to provide a cost-effective way to provide disaster recovery, provided the SnapMirror version requirements are met.

.Test ) Data migration


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 4 | Tester: |  | Date: | 
| Test requirements: | Intercluster LIFs on each node +
ONTAP versions within 2 releases (ie 9.16.1 -> 9.18.1) +
A secondary cluster running ONTAP (or replicate to the same cluster to a different volume) +
 +
*Unified ONTAP cluster must be at 9.16.1 if replicating FlexGroup volumes from NetApp AFX source to unified ONTAP destination |  |  | 
| Test procedure: +
Ensure intercluster interfaces exist.  +
Click Network -> Overview. +
 +
Click the magnifying glass to search for interfaces with the type of “intercluster.” +
 +
Type “intercluster” in the search field to find any intercluster interfaces. +
If there are none, move on to the next step to create intercluster interfaces. If they do exist, move to the following step to set up the cluster peer. +
 +
Create intercluster interfaces (if they do not already exist) +
Each node in both clusters should have at least one intercluster interface. +
 +
Navigate to Protection -> Overview and click “Add network interfaces”.  +
 +
 +
Configure the interfaces for each node, as shown below  +
 +
 +
Click save and confirm the interfaces. +
 +
  +
Verify the interfaces have been created from the “Network interfaces overview.” +
 +
Note: If necessary, make any edits to interfaces here. +
 +
Add a cluster peer via System Manager on the source ONTAP cluster. +
Navigate to (Protection -> Overview) +
 +
Click the  next to “Cluster peers” and click “Add cluster peers” or click  the “Add a cluster peer” button +
 +
To peer to a remote cluster, a passphrase will be needed.  +
Click “Launch remote cluster.” +
 +
Add the remote cluster management IP address and click “Launch.” +
 +
Generate passphrase +
This will open a new window to the NetApp AFX cluster to generate a new passphrase for cluster peer authentication. From here, copy the passphrase and add it to the unified ONTAP system. +
 +
Add the passphrase +
Verify if the intercluster IP addresses for the NetApp AFX cluster are populated. If everything looks good, click “Initiate cluster peering.” +
 +
Verify the cluster peer status +
If successful, you will see cluster peers listed under Protection -> Overview. Initially, the peer may show as “partial” with a red X next to the name. This can happen when the peer job is finishing. Eventually, the status should show a green check: +
 +
You can also check the cluster peer health from the command line. +
AFX::*> cluster peer health show +
Node       Cluster-Name                 Node-Name +
             Ping-Status               RDB-Health Cluster-Health Availability +
---------- --------------------------- --------- --------------- ------------ +
AFX-01 +
           unified                     unified-01 +
             Data: interface_reachable +
             ICMP: -                   true      true            true +
                                       unified-02 +
             Data: interface_reachable +
             ICMP: -                   true      true            true +
AFX-02 +
           unified                     unified-01 +
             Data: interface_reachable +
             ICMP: -                   true      true            true +
                                       unified-02 +
             Data: interface_reachable +
             ICMP: -                   true      true            true +
4 entries were displayed. +
 +
Establish SnapMirror from unified ONTAP to AFX. +
Use source volume with production datasets on unified ONTAP cluster to the NetApp AFX cluster.  +
Navigate to the volume using the left menu. (Storage -> Volumes). +
 +
Hover over the volume name and click the to expand the menu.  +
Select “Protect”. +
 +
Configure the SnapMirror settings and click “Protect” +
 +
If the above steps fail, you can attempt to create the relationship via the CLI. +
 +
CLI Steps +
Check the constituent count on the source volume’s FlexGroup volume. +
SnapMirror of FlexGroup volumes will require identical constituent counts on source and destination. +
AFX::> set advanced; volume show -vserver vs0 -volume dataset -fields constituent-count +
 +
Create a FlexGroup on the AFX cluster +
The volume will need the same number of constituent volumes + equal/greater size with a type of “DP.” +
AFX::> set advanced; vol create -volume dataset_dst -state online -size 2T -type DP -number-of-constituents [number from previous step] +
 +
Create the SnapMirror relationship +
AFX::> snapmirror create -source-path vs0:dataset -destination-path svm1:dataset_dst -vserver svm1 -throttle unlimited +
 +
Initialize the SnapMirror +
AFX::> snapmirror initialize -destination-path svm1:dataset_dst +
 +
Verify replication is progressing and eventually completed. Optional: Leverage EMS to send email notification when SnapMirror job is completed. +
 +
GUI steps +
Navigate to Protection -> Replication +
 +
Click on the SnapMirror relationship +
 +
Verify the status +
Is it healthy? What state is it in? What was the last transfer status? +
 +
CLI Steps +
AFX::*> snapmirror show +
                                                                       Progress +
Source            Destination Mirror  Relationship   Total             Last +
Path        Type  Path        State   Status         Progress  Healthy Updated +
----------- ---- ------------ ------- -------------- --------- ------- -------- +
vs0:dataset XDP  svm1:dataset_dst +
                              Snapmirrored +
                                      Idle           -         true    - +
 +
Compare source and destination datasets. +
Source and destination datasets can be compared via the CLI to see if the file counts are identical. This is an inexact science, but is useful for a start. +
 +
unified::*> vol show -vserver vs0 -volume dataset -fields files-used +
vserver volume  files-used +
------- ------- ---------- +
vs0     dataset 78001 +
AFX::*> vol show -vserver svm1 -volume dataset_dst -fields files-used +
vserver volume      files-used +
------- ----------- ---------- +
svm1    dataset_dst 78001 +
 +
Compare contents/checksums +
For a more accurate comparison, you will need to compare the actual contents of the volumes. For NFS, you can do that by mounting both volumes and running a diff command on the NFS client. +
For the source volume, the last common snapshot should be used as the path. +
 +
# mount /unifiedONTAPvol +
# mount /AFXONTAPvol +
# diff -r unifiedONTAPvol/.snapshot/lastcommonsnap/ AFXONTAPvol/ +
The command can take considerable time (depending on file count and size), as it will read the entirety of the files. But if both volumes are identical, you should see no differences in the listings. If you wish to avoid this potentially lengthy step, use the files used count comparisons from the vol show command. +
 +
Break the SnapMirror relationship and test ability to access and write to destination volume on NetApp AFX. +
From the NetApp AFX System Manager GUI, navigate to Protection -> Replication. +
 +
Hover over the relationship and use the  to expand the menu. Select “Break.” +
 +
Confirm the details and click “Break.” +
 +
Establish a SnapMirror from NetApp AFX to unified ONTAP with DR/backup as a goal. +
There are two ways to achieve this goal. One way is to create a separate, brand new SnapMirror to a new destination volume. The other way is to initiate a “reverse resync,” which will re-use the original source volume. The below covers both steps. You can perform both or you can choose one. +
 +
Destination ONTAP cluster will need to be on 9.16.1 or later to allow Advanced Capacity Balancing to be enabled. If it’s not possible to use a destination unified ONTAP cluster, use the NetApp AFX cluster as the destination instead. +
New SnapMirror steps +
Navigate to Storage -> Volumes +
 +
Hover over the volume name and click the to expand the menu. +
Select “Protect”. +
 +
Review the options and click “Protect.” +
 +
Reverse Resync steps: +
Navigate to Protection -> Replication. +
 +
Hover over the relationship and use the  to expand the menu. Select “Reverse Resync.” +
 +
Verify in the unified ONTAP destination cluster that the relationship appears when navigating to Protection -> Relationships. |  |  |  | 
| Expected outcome(s): +
A data protection relationship from unified ONTAP to NetApp AFX is established, and data migration is completed. +
Source and destination volume datasets are compared to verify successful migration. +
SnapMirror relationship is broken; destination volume is verified as writeable and ready for workload testing. +
OPTIONAL: Replicate from NetApp AFX to unified ONTAP |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[volume-management]]
=== Volume management

NetApp AFX makes some changes to how volumes are created and managed. This test aims to display some of those changes, show scale, and how volumes move automatically.

.Test ) Volume management.


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Error! Reference source not found. | Tester: |  | Date: | 
| Test requirements: | No specific requirements. |  |  | 
| Test procedure: +
Use the script found in the appendix to create a large number of volumes on the cluster. +
Review the location of the constituent volumes of the FlexGroup volumes. Note the balance of volume counts per node. Volume counts should be relatively evenly distributed (+/- 2). +
AFX::> vol show -volume name* -is-constituent true -fields size -node [node-name] +
Example: +
AFX::*> vol show -node AFX-01 +
… +
98 entries were displayed. << SVM root is the +1 +
 +
AFX::*> vol show -node AFX-02 +
… +
97 entries were displayed. +
 +
Create a new volume FlexGroup on a dedicated aggregate in admin privilege. Note the error.  +
AFX::*> set admin +
 +
AFX::> volume create -volume fg1 -aggr-list dataFA[tab] -aggr-list-multiplier 20 +
 +
Error: command failed: Aggregate "dataFA_2_p0_i1" cannot be used to create a volume on this platform. +
 +
Create a new FlexGroup volume on a specific node’s virtual aggregate using the -aggr-list-multiplier flag in diag priv. Use tab completion to suggest one of the virtual data aggregates. +
AFX::> set diag +
AFX::*> volume create -volume fg1 -aggr-list dataFA[tab] -aggr-list-multiplier 20 +
While NetApp AFX no longer leverages aggregates as a physical construct, there are still virtualized aggregates that “own” volumes. These provide a location for NVRAM commits to occur, since we still write the same way as unified ONTAP. By default, all volumes are created in the Storage Availability Zone and ONTAP handles the volume placement. +
View the volume count for each data aggregate after creating the FlexGroup volume. Note that the volumes counts are imbalanced. +
AFX::*> aggr show -aggregate data* -fields volcount +
aggregate      volcount +
-------------- -------- +
dataFA_2_p0_i1 31 +
dataFA_4_p0_i1 10 +
 +
Create a new FlexGroup volume without specifying the aggregate name and check the volume count again. Note how ONTAP is attempting to balance the placement across by placing new volumes evenly across nodes, but the imbalance is still present on the manually placed volumes. +
AFX::*> volume create -volume fg2 -auto-provision-as flexgroup +
 +
rtp-afx1k-c01::*> aggr show -aggregate data* -fields volcount +
aggregate      volcount +
-------------- -------- +
dataFA_2_p0_i1 41 +
dataFA_4_p0_i1 20 +
 +
The imbalance is present because when you manually override ONTAP volume placement, it disables the rebalance functionality (-atm-state). Check that in diag priv. +
rtp-afx1k-c01::*> vol show -vserver svm1 -volume fg1,fg2 -fields atm-state +
vserver volume atm-state +
------- ------ --------- +
svm1    fg1    disabled +
svm1    fg2    enabled +
 +
That can be re-enabled. Use the following command. +
rtp-afx1k-c01::*> set diag; vol modify -volume fg1 -atm-state enabled +
 +
After ~5 minutes, ONTAP runs a job that periodically rebalances the volume counts to even things out. You can either wait for that duration or manually start this process.  +
 +
After ~5 minutes, we see this: +
rtp-afx1k-c01::*> aggr show -aggregate data* -fields volcount,node +
aggregate      node             volcount +
-------------- ---------------- -------- +
dataFA_2_p0_i1 rtp-afx1k-c01-01 31 +
dataFA_4_p0_i1 rtp-afx1k-c01-02 30 +
To manually start the rebalance, a diag level command is used (and is not recommended to use on production workloads unless guided by NetApp support). +
AFX::> set diag +
AFX::*> debug smdb table atm_kick run +
 +
HA failover testing in a later part of this test plan will cover volume rebalancing there as well. +
If you need to delete volumes/clean up volumes, you can leverage the volume delete script in the Scripts section. |  |  |  | 
| Expected outcome(s): +
Volume counts will be balanced across nodes. +
Volume counts will rebalance when uneven. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[api-testingseamless-support-for-customer-automation]]
=== API testing/seamless support for customer automation

NetApp AFX is intended to provide a seamless ONTAP experience. Included in that is API parity between unified and NetApp AFX so that legacy automation suites using REST API calls to ONTAP will be plug-and-play into NetApp AFX.
If no current API-based automation suites are in use, then some basic REST API calls are provided to test functionality. See the appendix for examples.

.Test ) API testing/seamless support for customer automation


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 6 | Tester: |  | Date: | 
| Test requirements: | No specific requirements. |  |  | 
| Test procedure: +
Test your REST API calls against unified ONTAP. +
 +
If you are not already using standard automation REST calls against unified ONTAP, then leverage the example calls in the appendix of this document. +
 +
Test your REST API calls against NetApp AFX. +
If you are not already using standard automation REST calls against NetApp AFX, then leverage the example calls in the appendix of this document. |  |  |  | 
| Expected outcome(s): +
REST API calls used with unified ONTAP are tested. +
The same REST API calls are tested against NetApp AFX and are successful, with the exception of SAN-related and aggregate-related calls. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[performance-testing-configuration]]
=== Performance testing configuration

Performance testing is generally intended to find the edges of what a system can achieve in specific workload scenarios. Most of the time, the ONTAP default settings do not need to be adjusted to see good performance for most workloads, but in some cases, you may want to adjust some configurations to optimize the system. This section covers some genera considerations and configuration guidelines rather than serving as an actual test.

[[nfs-export-policy-configuration]]
=== NFS export policy configuration

Export policies in ONTAP are how access to NFS exports are controlled. Every volume requires an export policy to be set, with rules configured in the policy. If no rules are configured in a policy, that will be considered as "no access." 
For performance benchmarking, we are likely less concerned with permissions to the clients being used for testing and instead would like to avoid any permission-related errors.
As a result, it is recommended to ensure that any export policy rule is set to wide-open access for the data volume, but only to the clients being used to access datasets. In addition, the vsroot policy *must* allow read access in the policy for path traversal.
vsroot policy (uses "default" policy)

[source,console]
----
export-policy rule create -policyname default -clientmatch 0/0 -rorule any -rwrule never
----

data volume policy

[source,console]
----
export-policy create -policyname [name] -vserver [SVM]
export-policy rule create -policyname [name] -clientmatch [client1],[client2],..[clientN] -rorule any -rwrule any -superuser any -anon 0 -chown-mode unrestricted -ntfs-unix-security-ops ignore
----


NOTE: The NFS server configuration reference table and benchmark CLI command are consolidated in xref:setup.adoc#nfs-server-configuration[Setup: NFS Server Configuration].


[[volume-configuration]]
=== Volume configuration

The following section covers volume creation/configuration considerations and shows what options should be used during the initial creation.

[cols="1,1",options="header"]
|===
| Volume type | FlexGroup
| Creation method | CLI +
set diag; vol create -vserver [SVM] -volume [name] -size [size] -junction-path [/path] -unix-permissions 777 -files-set-maximum true -maxdir-size 4G -is-large-size-enabled true -snapshot-policy none -autosize-mode grow_shrink -policy [data policy] -snapdir-access false
| Defaults changed | Snapshot policy disabled +
Maxfiles increased +
Maxdirsize increased +
Large size enabled +
Autosize enabled +
UNIX permissions 777 +
File System Analytics disabled +
Snapdir access false
|===


[[special-considerations----flexgroup-volumes]]
==== Special considerations -- FlexGroup volumes

If the workload creates many large files (>1GB) in a single folder, modify the volume's workflow to data:

[source,console]
----
AFX::> set advanced; vol modify -vserver [SVM] -volume [FlexGroup name] -workflow data
----

If the workload is VMware datastores hosted on a FlexGroup volume, disable the -gdd option:

[source,console]
----
AFX::> set diag; vol modify -vserver [SVM] -volume [FlexGroup name] -granular-data disabled
----


[[why-snapshots-are-disabled]]
==== Why snapshots are disabled

In general, snapshots in ONTAP are not detrimental to overall system performance. However, in benchmarking, we would disable snapshots for two reasons:
* Granular control over the environment -- We can create snapshots when we want to create them to better control the scenarios when snapshots are created and make it easier to measure their impact.
* Data churn -- Many benchmark tests will create a lot of data and then subsequently delete that data, which will rapidly grow the size of any existing snapshots on the volume. To avoid space allocation issues, we disable snapshots.

NOTE: Snapdir access is also disabled to prevent unwanted filesystem crawls across snapshots.


[[mount-options]]
=== Mount options

Mount options, in general, are variable depending on use cases. This section attempts to show a general use case mount option list that was used in our internal performance testing. If the NFS server is configured properly (see above) then you won't need to specify NFS versions or wsize/rsize options.
Base options (applies to all clients/scenaros):

[source,console]
----
-o tcp,hard,intr
----


.Session trunking (OS-specific)


[source,console]
----
RHEL: trunkdiscovery
Ubuntu (depends on version): trunkdiscovery (newer releases)
                             max_connect=4 (older releases)
----

RDMA specific options

[source,console]
----
rdma,write=eager
----

Other mount options
Some workloads might benefit from special mount options during benchmark tests. The following table shows some of those options and what use cases might see performance improvements.

.Table ) Alternate NFS mount options and their use cases


[cols="1,1,1",options="header"]
|===
| NFS mount option | Description | Use case
| nocto | Disables "close-to-open" cache consistency. The client will not revalidate cached file attributes when a file is opened, relying instead on cached data even if it may be stale. | Read-heavy, single-client workloads where files rarely change (e.g., static web content, software libraries, read-only media archives). Not suitable for multi-client writes.
| cto | Enables close-to-open cache consistency (default). When a file is opened, the client checks with the server to ensure its cached copy is still valid. Guarantees that a file closed on one client is seen as up-to-date when opened on another. | Multi-client shared access workloads where data consistency matters (e.g., shared home directories, collaborative development environments).
| actimeo | Sets all attribute cache timeouts (acregmin, acregmax, acdirmin, acdirmax) to a single value in seconds. Controls how long the client trusts cached file/directory metadata before revalidating with the server. | Simplifying tuning when you want a uniform caching policy. High values benefit read-heavy/static workloads; low values (e.g., actimeo=0) suit rapidly changing data needing near-real-time consistency.
| acregmin | Sets the minimum time (seconds) the client caches attributes for a regular file before revalidating. Default is typically 3s. | Workloads with frequently updated small files where you want to fine-tune freshness vs. performance (e.g., log ingestion, config file polling).
| acregmax | Sets the maximum time (seconds) the client caches attributes for a regular file. Default is typically 60s. | Mostly-static file workloads where extending the max reduces metadata chatter (e.g., large read-only datasets, package repositories).
| acdirmin | Sets the minimum time (seconds) the client caches attributes for a directory before revalidating. Default is typically 30s. | Workloads with frequent directory listing or creation (e.g., build systems, mail spools with Maildir format) where directory freshness matters.
| acdirmax | Sets the maximum time (seconds) the client caches attributes for a directory. Default is typically 60s. | Stable directory structures that rarely change — raising this reduces GETATTR calls (e.g., large static directory trees, archival storage).
| clientaddr | Specifies the client IP address to advertise to the NFS server for callback communication (NFSv4/v4.1+). The server uses this address to send delegation recalls and other callbacks. | Multi-homed clients or environments with complex networking (e.g., clients with multiple NICs, VPN/overlay networks, or NAT) where the auto-detected address may be incorrect.
| nconnect | Creates multiple TCP connections (up to the specified count) to the NFS server for a single mount, allowing parallel I/O over separate connections. | High-throughput, I/O-intensive workloads that are bottlenecked by a single TCP stream (e.g., large file transfers, HPC/scientific computing, video editing, database backups, big data analytics). Particularly beneficial on high-bandwidth networks (10 GbE+).
| krb5* | Specifies what Kerberos security flavor to use with the mount. Requires Kerberos configuration to work properly. See TR-4616 NFS Kerberos with Active Directory for details. | Securing NFS mounts; has a negative impact on performance.
|===


[[client-configuration]]
=== Client configuration

The client configuration used for our internal benchmarking is covered in the Clients section at the beginning of this document. The following contains some additional configuration considerations. This list is not considered exhaustive and will be modified over time to accommodate additional use cases/scenarios.

[[nfs-readahead]]
==== NFS readahead

From:  
_NFS read-ahead predictively requests blocks from a file in advance of I/O requests by the application. It's designed to improve client sequential read throughput. Until recently, all modern Linux distributions set the read-ahead value to be equivalent of 15 times the mounted filesystems rsize._
_RHEL 8.3 and Ubuntu 18.04 introduced changes that might negatively impact client sequential read performance. Unlike earlier releases, these distributions set read-ahead to a default of 128 KiB regardless of the rsize mount option used. Upgrading from releases with the larger read-ahead value to releases with the 128-KiB default experienced decreases in sequential read performance. However, read-ahead values may be tuned upward both dynamically and persistently. For example, testing with SAS GRID found the 15,360 KiB read value optimal compared to 3,840 KiB, 960 KiB, and 128 KiB. Not enough tests have been run beyond 15,360 KiB to determine positive or negative impact._
For steps on how to view/set NFS readahead values, see: 

[[network-configuration]]
=== Network configuration

The following section covers some general networking guidance for client and storage networking. These are based on the internal benchmark tests we have done.

[[storage-network-considerations]]
==== Storage network considerations

* At least one data IP address per node, per SVM (more per node is better)
* Maximum of 16 IP addresses per node, per SVM
* All data interfaces routable to all clients
* Bonded/teamed ports per node using LACP
* MTU size of 9000 (end to end)
* Priority flow control (PFC priority 3) enabled when using RDMA
* DNS round robin/load balancing configured to include all data interface IP addresses

[[client-network-considerations]]
==== Client network considerations

* Dual NICs bonded for RoCE (LACP)
* RX/TX ring buffers set to 8192
* PFC and DSCP configured per NIC (when using RDMA)
* RoCE traffic class set using cma_roce_tos (when using RDMA)
* sunrpc.rdma_slot_table_entries set to 200

[[ontap-feature-considerations]]
=== ONTAP feature considerations

The following covers specific ONTAP feature configuration modifications that are not covered in the sections above.

[[disable-storage-efficiencies]]
==== Disable storage efficiencies

In general, storage efficiencies are one of the selling points for a production workload, as they can generate large space savings across a variety of workloads. However, in performance benchmarking, they offer less value (as many simulated workloads are either uncompressible or are zero-byte workloads and always deduplicating). As a result, we recommend disabling all storage efficiencies while performing benchmark tests.

[source,console]
----
vol efficiency off -volume [name] -vserver [SVM]

aggr efficiency modify -aggregate data* -cross-volume-background-dedupe false -cross-volume-inline-dedupe false

aggr efficiency wise-tsse modify -aggregate data* -enable-workload-informed-tsse false
----


NOTE: Aggressive Readahead feature configuration, caveats, and statistics are covered in xref:feature-aggressive-readahead.adoc[Aggressive Readahead Feature Test].


[[customer-workload-testing--real-data]]
=== Customer workload testing -- real data

The goal of these workload tests is to show that real data workloads can be ported over to NetApp AFX seamlessly and can potentially provide performance benefits over unified ONTAP -- particularly when growing the compute side of the cluster. 

NOTE: For NFS considerations, see the Appendix in this document.


.Test ) Customer workload testing -- real workloads, real data


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 7 | Tester: |  | Date: | 
| Test requirements: | No specific requirements. |  |  | 
| Test procedure: +
Mount NetApp AFX volume using NAS protocol of your choice. +
Mount using NFS or SMB. For best results, use multiple simultaneous clients rather that testing a single client’s performance. +
 +
Find the export path of your data volume in System Manager. +
 +
Mount the volume using NFS.  +
Optionally, include the mount path in /etc/fstab or automounter* +
*Recommended NFS versions and mount options are found in the NFS considerations above. +
Run designated workloads against existing datasets that have been migrated over from unified ONTAP. While benchmarks are running, move on to Test 5) Performance Monitoring. +
Test real-world data using everyday workloads. As workloads are running, test the limits of NetApp AFX by adding more clients or more jobs to the workload to push the limits of scale. |  |  |  | 
| Expected outcome(s): +
Workloads should not need additional configuration or changes to run properly using NetApp AFX.  +
Performance should be as good or better than unified ONTAP. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[customer-workload-testing--performance-benchmarks]]
=== Customer workload testing -- Performance benchmarks

In lieu of - or in addition to -- testing real data workloads, storage benchmark tests can also be run against the NetApp AFX cluster to display some of the potential performance.
For EDA workloads, we can leverage SPEC SFS 2020 EDA for benchmarking. This benchmark can also be used for general testing of small random IO (including high metadata) and larger sequential IO. 
For AI/ML workloads, we will leverage MLcommons, which can also act as a throughput-specific benchmark. 
For details on installing, configuring and running SpecSFS or MLcommons, see the Appendix of this document.

.Test ) Customer workload testing - benchmarks


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 8 | Tester: |  | Date: | 
| Test requirements: | No specific requirements.  +
Benchmark tests are run using specific parameters stated in this document. |  |  | 
| Test procedure: +
Create a FlexGroup volume in the NetApp AFX cluster. +
 +
Navigate to the Storage -> Volumes menu in System Manager +
 +
Click + Add +
 +
Enter the volume name, capacity and select “High throughput” to create a FlexGroup +
 +
Optionally, click “More options” to disable/enable data protection features and add export policies and rules +
 +
Click save. +
Mount NetApp AFX volume using NAS protocol of your choice. +
Mount using NFS or SMB. For best results, use multiple simultaneous clients rather that testing a single client’s performance. +
 +
Find the export path of your data volume in System Manager. +
 +
Mount the volume using NFS.  +
Optionally, include the mount path in /etc/fstab or automounter* +
*Recommended NFS versions and mount options are found in the NFS considerations in the Appendix of this document.. +
 +
Generate datasets. +
For detailed steps on how to run the benchmarks, see the appendix of this document. +
 +
Run benchmarks on datasets. While benchmarks are running, move on to the Performance Monitoring test plan. |  |  |  | 
| Expected outcome(s): +
Benchmarks should show the performance capabilities of this system. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[performance-monitoring]]
=== Performance monitoring

The goal of this test is to illustrate the performance monitoring capabilities of NetApp AFX and how it can integrate into current performance monitoring tools used by unified ONTAP and how understanding ONTAP performance should have little to no learning curve from unified ONTAP.
NetApp System Manager can be used for basic performance monitoring and is covered in the test below.
NetApp Harvest can be used to monitor performance at a more advanced level: 
NetApp Harvest - GitHub

.Test ) Performance monitoring


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 9 | Tester: |  | Date: | 
| Test requirements: | No specific requirements. +
Performance testing being run during monitoring, |  |  | 
| Test procedure: +
Verify performance tests are running. +
Performance tests can be real data or benchmarks. +
From the System Manager GUI +
Login to System Manager. On the main page, you can see performance graphs on the right. This shows if there is activity in the cluster. +
 +
To verify if this activity is happening on the volume you created, you can click on Storage->Volumes and then click on the volume you created. +
 +
Use CLI statistics to capture performance information. +
 +
Cluster statistics can be captured in real time with “statistics show-periodic” +
AFX::*> statistics show-periodic +
AFX: cluster.cluster: 5/8/2025 01:34:46 +
  cpu  cpu    total                     fcache             total    total data     data     data cluster  cluster  cluster     disk     disk     pkts     pkts +
  avg busy      ops  nfs-ops cifs-ops      ops spin-ops     recv     sent busy     recv     sent    busy     recv     sent     read    write     recv     sent +
 ---- ---- -------- -------- -------- -------- -------- -------- -------- ---- -------- -------- ------- -------- -------- -------- -------- -------- -------- +
   7%  13%      777      777        0        0      678    699MB   2.67MB   2%    698MB   2.37MB      0%    326KB    300KB   8.39MB   31.7KB   482985    36295 +
   7%  13%      907      907        0        0      795    785MB   2.89MB   2%    784MB   2.59MB      0%    334KB    307KB   12.2MB   15.8KB   542564    39790 +
   8%  14%      797      797        0        0      705    707MB   2.75MB   1%    706MB   2.46MB      0%    337KB    304KB    109MB    341MB   488621    37404 +
cluster: cluster.cluster: 5/8/2025 01:34:52 +
  cpu  cpu    total                     fcache             total    total data     data     data cluster  cluster  cluster     disk     disk     pkts     pkts +
  avg busy      ops  nfs-ops cifs-ops      ops spin-ops     recv     sent busy     recv     sent    busy     recv     sent     read    write     recv     sent +
 ---- ---- -------- -------- -------- -------- -------- -------- -------- ---- -------- -------- ------- -------- -------- -------- -------- -------- -------- +
Minimums: +
   7%  13%      777      777        0        0      678    699MB   2.67MB   1%    698MB   2.37MB      0%    326KB    300KB   8.39MB   15.8KB   482985    36295 +
Averages for 3 samples: +
   7%  13%      827      827        0        0      726    730MB   2.77MB   1%    730MB   2.47MB      0%    332KB    304KB   43.5MB    113MB   504723    37829 +
Maximums: +
   8%  14%      907      907        0        0      795    785MB   2.89MB   2%    784MB   2.59MB      0%    337KB    307KB    109MB    341MB   542564    39790 +
 +
For volume-level: +
AFX::*> qos statistics volume performance show -volume dataset -vserver svm1 +
Workload            ID     IOPS       Throughput    Latency +
--------------- ------ -------- ---------------- ---------- +
-total-              -      854       838.93MB/s  1178.00us +
-total-              -      586       561.70MB/s  1190.00us +
-total-              -     1005       985.07MB/s  1177.00us +
Collect protocol-level statistics during performance tests. +
Performance tests can be real data or benchmarks. +
From the command line, you can run “statistics start” to begin a stats collection during a specific job run. For this example, we will collect NFSv4.1 statistics. You can run these statistics at any time, but it is best to run these before starting a benchmark or data workload and then stopping them when the job is complete. These commands can be run in advanced privilege. +
AFX::> set advanced -confirmations off +
 +
AFX::*> statistics start -object nfsv4_1 -vserver svm1 -sample-id unet3d_datagen +
Statistics collection is being started for sample-id: unet3d_datagen +
 +
[run test to completion] +
 +
AFX::*> statistics stop -sample-id unet3d_datagen +
Statistics collection is being started for sample-id: unet3d_datagen +
 +
Once the statistics are stopped, you can view all the counter collected with: +
AFX::*> statistics show -sample-id unet3d_datagen +
 +
To view specific counters, you can use the counter name or wildcards. For instance, to see all GETATTR values: +
AFX::*> statistics show -sample-id unet3d_datagen -counter *getattr* +
 +
Object: nfsv4_1 +
Instance: svm1 +
Start-time: 5/8/2025 01:44:16 +
End-time: 5/8/2025 01:49:55 +
Elapsed-time: 339s +
Scope: cluster +
 +
    Counter                                                     Value +
    -------------------------------- -------------------------------- +
    getattr_avg_latency                                          21us +
    getattr_latency_hist                                            - +
                                <6us                               24 +
                               <10us                               52 +
                               <14us                              806 +
                               <20us                             1131 +
                               <40us                              960 +
                               <60us                               30 +
                              <200us                                8 +
                              <400us                               17 +
    getattr_success                                              3028 +
    getattr_total                                                3028 +
 +
To see a breakdown of the workload percentages: +
AFX::*> statistics show -sample-id unet3d_datagen -counter *percent* +
 +
Object: nfsv4_1 +
Instance: svm1 +
Start-time: 5/8/2025 01:44:16 +
End-time: 5/8/2025 01:49:55 +
Elapsed-time: 339s +
Scope: cluster +
 +
    Counter                                                     Value +
    -------------------------------- -------------------------------- +
    compound_percent                                              33% +
    putfh_percent                                                 33% +
    sequence_percent                                              33% +
    write_percent                                                 32% +
 +
To see a breakdown of read and write sizes: +
cluster::*> statistics show -sample-id unet3d_datagen -counter *size_hist* +
 +
Object: nfsv4_1 +
Instance: svm1 +
Start-time: 5/8/2025 01:44:16 +
End-time: 5/8/2025 01:49:55 +
Elapsed-time: 339s +
Scope: cluster +
 +
    Counter                                                     Value +
    -------------------------------- -------------------------------- +
    nfs41_write_size_histo                                          - +
                              <=512B                                7 +
                               <=2KB                                5 +
                               <=4KB                               24 +
                               <=8KB                                6 +
                              <=16KB                               18 +
                              <=32KB                              108 +
                              <=64KB                              138 +
                             <=128KB                              204 +
                             <=256KB                              315 +
                             <=512KB                              471 +
                               <=1MB                           207785 |  |  |  | 
| Expected outcome(s): +
Benchmarks should show the performance capabilities of this system. +
Performance statistic collection should be nearly identical to ONTAP. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[capacity-management]]
=== Capacity management

Viewing and managing capacity in NetApp AFX has been streamlined to improve simplicity and understanding of what capacity you actually have available. Aggregates as a managed construct are removed. Instead, volumes and the new Storage Availability Zone concept are how we view and managed capacity. This test plan shows different ways capacity is managed in NetApp AFX.

.Test ) Capacity management


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 10 | Tester: |  | Date: | 
| Test requirements: | No specific requirements.  +
Performance testing being run during live node additions. |  |  | 
| Test procedure – GUI: +
View capacity in the dashboard. +
 +
 +
From the CLI +
Display the Storage Availability Zone +
AFX::> storage availability-zone show +
Display the cluster space +
AFX::> cluster space show |  |  |  | 
| Expected outcome(s): +
Capacity views should be easy to understand. +
Storage availability zones should simplify capacity use. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[compute-scaling-optional]]
=== Compute scaling (optional)

One of the main benefits of NetApp AFX is the ability to scale compute and capacity independently. In this test, we will add 2 additional storage nodes to a 2-node NetApp AFX cluster during live workloads to verify that node additions are not only nondisruptive, but also increase performance scale linearly as volumes are rebalanced across nodes. This can also be done with other node count options (ie, starting with 4 nodes and adding 4 more nodes for an 8 node cluster).

.Test ) Node additions during live workloads


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 11 | Tester: |  | Date: | 
| Test requirements: | No specific requirements. +
Performance running during live node additions. |  |  | 
| Test procedure: +
Ensure benchmarks or performance workloads are running during these tests. Note the current average throughput and IOPS. +
AFX::> set advanced +
AFX::*> qos statistics volume performance show -vserver svm1 -volume [volname] +
 +
Check volume location of current nodes. Note the number of volumes per node. +
AFX::> set advanced +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node * +
 +
Log into the service processor of the node(s) you wish to add to the cluster. +
From the prompt, type “system console” to access the node’s console. If the node is not at the LOADER prompt, you can use ctl+d to exit to the BMC/service processor prompt. Type “system reset”, answer y for dirty shutdown, then “system console” to watch the boot process. Hit ctl+c when you see the “interrupt Autoboot” message. +
Once at the LOADER prompt, run the following: +
set-defaults +
setenv bootarg.init.unjoined true +
saveenv +
Then, boot the node to the boot menu prompt. +
LOADER> boot_ontap menu +
 +
Select option 4 from the menu. +
Please choose one of the following: +
 +
(1)  Normal Boot. +
(2)  Boot without /etc/rc. +
(3)  Change password. +
(4)  Initialize and configure system. +
(5)  Maintenance mode boot. +
(6)  Update flash from backup config. +
(7)  Install new software first. +
(8)  Reboot node. +
(9)  Clean System Configuration. +
(10) Set Onboard Key Manager recovery secrets. +
(11) Configure node for external key management. +
Selection (1-11)? 4 +
 +
If prompted, type yes: +
WARNING: This node may not have been properly unjoined from an existing cluster,                                                                              please confirm before using option (4) +
 +
WARNING: This node may not have been properly unjoined from an existing cluster.                                                                              Please confirm before continuing with option 4. +
Zero disks, reset config and install a new file system?: yes +
If you get sent back to LOADER from here, type boot_ontap at the LOADER prompt +
 +
Use the cluster setup wizard to configure a node management LIF/subnet/gateway. This will be used by System Manager to detect the node for addition into the cluster. Places to input information highlighted in yellow. +
Welcome to the cluster setup wizard. +
 +
You can enter the following commands at any time: +
  "help" or "?" - if you want to have a question clarified, +
  "back" - if you want to change previously answered questions, and +
  "exit" or "quit" - if you want to quit the cluster setup wizard. +
     Any changes you made before quitting will be saved. +
 +
You can return to cluster setup at any time by typing "cluster setup". +
To accept a default or omit a question, do not enter a value. +
 +
This system will send event messages and periodic reports to NetApp Technical +
Support. To disable this feature, enter +
autosupport modify -support disable +
within 24 hours. +
 +
Enabling AutoSupport can significantly speed problem determination +
and resolution, should a problem occur on your system. +
For further information on AutoSupport, see: +
https://support.netapp.com/autosupport/ +
 +
Type yes to confirm and continue {yes}: yes +
May 16 02:26:09 [localhost:asup.general.optout:notice]: AutoSupport will be enabled 24 hours after system initialization. +
 +
Enter the node management interface port [e0M]: +
Enter the node management interface IP address: 10.232.12.128 +
Enter the node management interface netmask: 255.255.254.0 +
Enter the node management interface default gateway: 10.232.12.1 +
A node management interface on port e0M with IP address 10.232.12.128 has been created. +
 +
Press CTL+C and enter the cluster CLI to modify the cluster interconnect IP addresses, as they auto create and may not be routable on your network. If you get a login: prompt, use admin. There will be no password here. +
This step is only needed if the other cluster interfaces on existing ndoes do not use the 169.254.x.x addresses that ONTAP auto creates. In most cases, you can leave these as defaults. +
 +
::> net int show -role cluster +
  (network interface show) +
            Logical    Status     Network            Current       Current Is +
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home +
----------- ---------- ---------- ------------------ ------------- ------- ---- +
Cluster +
            clus1        up/up    169.254.118.206/16 localhost     e7a     true +
            clus2        up/up    169.254.220.172/16 localhost     e7b     true +
2 entries were displayed. +
 +
::> net int modify -vserver Cluster -lif clus1 -address 192.168.76.222 +
  (network interface modify) +
 +
::> net int modify -vserver Cluster -lif clus2 -address 192.168.76.226 +
  (network interface modify) +
 +
Repeat the above setup steps on the other NetApp AFX node(s). +
 +
From here, access the System Manager window via the cluster management IP. Navigate to Cluster -> Overview and click on the “Nodes” tab. +
 +
 +
At the bottom of the page, you should see a section called “Not part of this cluster” and your new nodes below that. Click “+ Add” to add the node to the cluster.  +
An odd number of nodes cannot be added to a cluster. +
If the nodes are discovered before the cluster interconnect IP addresses are changed, then you will need to re-discover the nodes by exiting the window and navigating back. +
If the GUI addition does not work, try the CLI command cluster add-node instead If issues persist, utilize contact NetApp support or reach out to [email]. +
 +
 +
Use the “Add nodes” screen to fill in your information. Management IP addresses can be added manually or by using a subnet. +
 +
 +
 +
 +
Log into the cluster CLI. Monitor the node add status. +
AFX::*> add-node-status +
  (cluster add-node-status) +
 +
 +
Node Name        Cluster IP          Status              Error Reason +
---------------- ------------------- ------------------- -------------------------- +
AFX-01           192.168.76.221      success +
AFX-03           192.168.76.226      node-initialization +
AFX-04           192.168.76.220      node-initialization +
AFX-02           192.168.76.224      success +
4 entries were displayed. +
 +
OPTIONAL: Log into the system console of the nodes being added via the service processor and observe the steps being performed. +
 +
Once the node adds have completed, check the volume placement across all nodes. +
AFX::> set advanced +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-01 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-02 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-03 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-04 +
 +
Eventually, volumes should be distributed evenly across all nodes. Check back every 5 minutes or so. +
If disks are unavailable to one of the nodes (ie, bad switch config, bad cabling, card issues), then nodes will not add properly. +
If the node does not have two healthy cluster LIFs (ie a cluster port is down), the node will not add properly. +
Volumes will not move to unhealthy nodes/incomplete node joins. +
 +
Add/configure new network interfaces for your SVM on a per-node basis to add performance to the workload. Add at least one per node for NFSv3 and at least two per node if using NFSv4.x. +
AFX::> net int create -vserver [SVM] -lif [name] -address [10.10.10.10] -netmask [255.255.255.0] -home-node [node1] -home-port [port] -rdma-protocols [optional] -broadcast-domain [optional] +
..  +
AFX::> net int create -vserver [SVM] -lif [name] -address [10.10.10.10] -netmask [255.255.255.0] -home-node [node4] -home-port [port] -rdma-protocols [optional] -broadcast-domain [optional]  +
 +
If you are using pNFS, you clear the device caches to ensure the new interfaces get picked up. +
AFX::> set diag -c off +
AFX::*> pnfs lif-mapping-cache flush -node * +
AFX::*> pnfs devices cache flush -node * -vserver [SVM1] +
AFX::*> pnfs devices invalidate -global-device-table-id * +
 +
Verify if performance has increased for the currently running workload (throughput, CPU utilization, IOPS, etc.) +
AFX::> set advanced +
AFX::*> qos statistics volume performance show -vserver svm1 -volume [volname] +
From System Manager, you can view the performance graph. |  |  |  | 
| Expected outcome(s): +
Adding new nodes to the cluster should be nondisruptive. +
Volume moves should happen automatically and be nondisruptive. +
Performance should scale up linearly. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


[[node-failure-behavior]]
=== Node failure behavior

In NetApp AFX, storage failovers and givebacks allow for workloads to operate even through disruptions to nodes. One main difference, however, is that volumes owned by nodes will be automatically moved evenly across surviving nodes after a time period (~17 minutes) where the cluster verifies the node is truly down. In unified ONTAP, volumes would only move to the HA partner. 
This test's goal is to not only show that failovers and givebacks are capable of operating nearly identical to unified ONTAP, but also will show that storage administrators no longer need to factor in volume counts when sizing clusters greater than 4 nodes in size because NetApp AFX will rebalance volumes across all nodes in storage failover scenarios rather than allowing a partner node to be overcommitted.

NOTE: Failover here will be generated by node panic, which will automatically perform a call home to generate a case (provided ASUP is enabled). We will send a test ASUP prior to that to inform support that the cluster is under maintenance.


.Test ) Node failure behavior


[cols="1,1,1,1,1",options="header"]
|===
| Section | Details |  |  | 
| Test 12 | Tester: |  | Date: | 
| Test requirements: | No specific requirements. +
Benchmarks or performance workloads are active. |  |  | 
| Test procedure: +
Log into the cluster via the cluster management LIF. +
Verify benchmarks or performance workloads are running during these tests. +
AFX::> set advanced +
AFX::*> statistics show-periodic -counter nfs-ops +
AFX: cluster.cluster: 5/15/2025 18:18:17 +
  nfs-ops +
 -------- +
     3455 +
     5253 +
If there are NFS ops in progress, then the workload is active. +
 +
Check and note current volume locations across all nodes. +
AFX::> set advanced +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-01 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-02 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-03 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-04 +
 +
Send an Autosupport to show the node will be under maintenance/testing. +
AFX::> autosupport invoke -node * -type test -message "POC maintenance" +
 +
Panic node4 +
AFX::> node run -node AFX-04 +
Type 'exit' or 'Ctrl-D' to return to the CLI +
AFX-04> priv set diag +
Warning: These diagnostic commands are for use by NetApp +
         personnel only. +
AFX-04*> panic +
This process can take a long time due to the size of the core files. Booting back up immediately may not be possible. +
 +
While the nodes are in takeover, check the network interfaces and if they have been migrated. +
AFX::*> net int show -vserver SVM1 -fields is-home,is-home,home-node,home-port,curr-node,curr-port +
“is-home false” means the interface has been migrated from its home node. +
 +
Check the volume locations for each node. Note and compare to before takeover.  +
Volume moves after failover can take roughly 17-22 minutes as ONTAP waits to verify the node is actually down. But once they are enacted, they will complete quickly. +
AFX::> set advanced +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-01 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-02 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-03 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-04 +
 +
View the volume move status. +
AFX::*> vol move show -vserver svm1 -instance +
 +
Check the EMS messages to see if the volumes have moved. +
AFX::> event log show +
 +
Verify if performance has changed for currently running workload (throughput, CPU utilization, IOPS, etc.) and if operations have experienced noticeable disruption.  +
Use the performance monitoring steps in the Performance monitoring test plan above. +
 +
Boot the node by logging into the service processor and access the system console. +
SP-CLI> system console +
LOADER> boot_ontap +
 +
Verify that the node has come back up. After a period of time, it will automatically give back. Check to see if it has performed an automatic giveback. This should take roughly 10 minutes after the nodes boots.  +
AFX::system*> storage failover show +
                              Takeover +
                                 of +
Node           Partner        Possible State Description +
-------------- -------------- -------- --------------------------------------- +
AFX-01 +
               AFX-04         true     Connected to AFX-04, +
                                       Partial giveback +
AFX-02 +
               AFX-03         true     Connected to AFX-03 +
                +
AFX-03 +
               AFX-02         true     Connected to AFX-02 +
                +
AFX-04 +
               AFX-01         true     Connected to AFX-01. +
                                       Waiting for cluster applications to +
                                       come online on the local node. +
 +
If in “Partial Giveback” wait another 5 minutes and rerun the “show” command. +
AFX::system*> storage failover show +
                              Takeover +
                                 of +
Node           Partner        Possible State Description +
-------------- -------------- -------- --------------------------------------- +
AFX-01 +
               AFX-04         true     Connected to AFX-04 +
                +
AFX-02 +
               AFX-03         true     Connected to AFX-03 +
                +
AFX-03 +
               AFX-02         true     Connected to AFX-02 +
                +
AFX-04 +
               AFX-01         true     Connected to AFX-01 +
                +
4 entries were displayed. +
 +
During giveback, verify if performance has changed for currently running workload (throughput, CPU utilization, IOPS, etc.) and if operations have experienced noticeable disruption. Operations using stateful NAS (such as SMB and NFSv4.x) will experience some disruption due to locking exchange.  +
Use the steps in the performance monitoring test plan. +
 +
Check the home status of the network interfaces.  +
AFX::> net int show -is-home false +
 +
If the interfaces are not at home, revert them. +
AFX::> net int revert * +
 +
After giveback is complete, verify the volume locations. +
AFX::> set advanced +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-01 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-02 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-03 +
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-04 +
 +
View the volume move status. +
AFX::*> vol move show -vserver svm1 -instance |  |  |  | 
| Expected outcome(s): +
The selected node will panic. +
Cluster will send AutoSupport to NetApp support. +
Cluster will perform give back to normal operations. +
Storage failover should not interrupt operations. +
Volumes should move across nodes to balance performance in between 17-22 minutes after failover. +
Performance should not see a noticeable decrease once volumes are moved. +
Givebacks should rebalance volumes and performance back to the initial state. +
Volumes will not necessarily return back to the same nodes they originated on. |  |  |  | 
| Test results: |  |  |  | 
| Test summary: |  |  |  | 
| Comments: |  |  |  | 
|===


NOTE: Optional tests 13-16 (FlexCache, S3, Snapshots/SnapMirror, NDU) are linked from xref:test-plans.adoc[Test Plans Overview].


[[optional-new-feature-tests]]
=== OPTIONAL: New feature tests

NetApp AFX includes some new features in the ONTAP 9.19.1 release that can be tested as part of this plan, including:
* Global deduplication
* Dynamic storage efficiency
* Aggressive readahead
* FabricPool (cold data tiering; ONTAP 9.19.1P2 and later)
This section covers configuration details and how to test some of the functionality at a high level.
