= Scripts
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book

xref:appendix.adoc[← Back to Appendix]

Scripts to support volume management, LIF management, cluster reinitialization, and NAS benchmarking.


[[scripts]]
== Scripts

The following section contains scripts that can be used with these test plans.

[[volume-creation-and-deletion-scripts]]
=== Volume creation and deletion scripts

The following scripts can be used to create/delete data volumes.

[[lif-creation-and-cleanup-scripts]]
=== LIF creation and cleanup scripts

The following scripts can be used to create/delete network interfaces.

[[netapp-afx-reinitialization-script]]
=== NetApp AFX reinitialization script

If you need to re-initialize a cluster during this test plan, the following script can help with that.
Be sure to review the README file. Reach out to  for any questions or improvements.

[[maximum-files-monitor]]
=== Maximum files monitor

This script can be run as a scheduled job and will monitor a volume for its inode usage.

[[nas-performance-benchmark-scripts-benchmarkingontap-repo]]
=== NAS Performance Benchmark Scripts (Benchmarking/ONTAP repo)

A collection of NAS-specific benchmark and automation scripts is maintained in the Benchmarking/ONTAP repository on GitHub. This includes scripts for volume and LIF management referenced throughout this test plan.
link:https://github.com/whyistheinternetbroken/Benchmarking/tree/main/ONTAP[https://github.com/whyistheinternetbroken/Benchmarking/tree/main/ONTAP]
* link:https://github.com/whyistheinternetbroken/Benchmarking/tree/main/ONTAP/volumes[Volume creation and deletion scripts]
* link:https://github.com/whyistheinternetbroken/Benchmarking/tree/main/ONTAP/networking[LIF creation and cleanup scripts]
// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:appendix-statistics-counters.adoc[< Previous]
>| xref:blank-test-template.adoc[Next >]
|===
// navigation-links:end
