= Test 12: Node failure behavior
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book

xref:test-plans.adoc[← Back to Test Plans]

[[node-failure-behavior]]
== Node failure behavior

In NetApp AFX, storage failovers and givebacks allow for workloads to operate even through disruptions to nodes. One main difference, however, is that volumes owned by nodes will be automatically moved evenly across surviving nodes after a time period (~17 minutes) where the cluster verifies the node is truly down. In unified ONTAP, volumes would only move to the HA partner.
This test's goal is to not only show that failovers and givebacks are capable of operating nearly identical to unified ONTAP, but also will show that storage administrators no longer need to factor in volume counts when sizing clusters greater than 4 nodes in size because NetApp AFX will rebalance volumes across all nodes in storage failover scenarios rather than allowing a partner node to be overcommitted.

*Note:* Failover here will be generated by node panic, which will automatically perform a call home to generate a case (provided ASUP is enabled). We will send a test ASUP prior to that to inform support that the cluster is under maintenance.

[cols="1",%autowidth]
|===
| *Test plan 12 - Node failure behavior*

a| *Test procedure:*

. Log into the cluster via the cluster management LIF. Verify benchmarks or performance workloads are running during these tests.
+
[source,console]
----
AFX::> set advanced
AFX::*> statistics show-periodic -counter nfs-ops
AFX: cluster.cluster: 5/15/2025 18:18:17
  nfs-ops
 --------
     3455
     5253
If there are NFS ops in progress, then the workload is active.
----

. Check and note current volume locations across all nodes.
+
[source,console]
----
AFX::> set advanced
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-01
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-02
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-03
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-04
----

. Send an Autosupport to show the node will be under maintenance/testing.
+
[source,console]
----
AFX::> autosupport invoke -node * -type test -message "POC maintenance"
----

. Panic node4
+
[source,console]
----
AFX::> node run -node AFX-04
Type 'exit' or 'Ctrl-D' to return to the CLI
AFX-04> priv set diag
Warning: These diagnostic commands are for use by NetApp
         personnel only.
AFX-04*> panic
This process can take a long time due to the size of the core files. Booting back up immediately may not be possible.
----

. While the nodes are in takeover, check the network interfaces and if they have been migrated.
+
[source,console]
----
AFX::*> net int show -vserver SVM1 -fields is-home,is-home,home-node,home-port,curr-node,curr-port
“is-home false” means the interface has been migrated from its home node.
----

. Check the volume locations for each node. Note and compare to before takeover. Volume moves after failover can take roughly 17-22 minutes as ONTAP waits to verify the node is actually down. But once they are enacted, they will complete quickly.
+
[source,console]
----
AFX::> set advanced
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-01
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-02
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-03
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-04
----

. View the volume move status.
+
[source,console]
----
AFX::*> vol move show -vserver svm1 -instance
----

. Check the EMS messages to see if the volumes have moved.
+
[source,console]
----
AFX::> event log show
----

. Verify if performance has changed for currently running workload (throughput, CPU utilization, IOPS, etc.) and if operations have experienced noticeable disruption. Use the performance monitoring steps in the Performance monitoring test plan above.

. Boot the node by logging into the service processor and access the system console.
+
[source,console]
----
SP-CLI> system console
LOADER> boot_ontap
----

. Verify that the node has come back up. After a period of time, it will automatically give back. Check to see if it has performed an automatic giveback. This should take roughly 10 minutes after the nodes boots.
+
[source,console]
----
AFX::system*> storage failover show
                              Takeover
                                 of
Node           Partner        Possible State Description
-------------- -------------- -------- ---------------------------------------
AFX-01
AFX-04         true     Connected to AFX-04,
                                       Partial giveback
AFX-02
AFX-03         true     Connected to AFX-03
----
+
[source,console]
----
AFX-03
AFX-02         true     Connected to AFX-02
----
+
[source,console]
----
AFX-04
AFX-01         true     Connected to AFX-01.
                                       Waiting for cluster applications to
                                       come online on the local node.
----

. If in “Partial Giveback” wait another 5 minutes and rerun the “show” command.
+
[source,console]
----
AFX::system*> storage failover show
                              Takeover
                                 of
Node           Partner        Possible State Description
-------------- -------------- -------- ---------------------------------------
AFX-01
AFX-04         true     Connected to AFX-04
----
+
[source,console]
----
AFX-02
AFX-03         true     Connected to AFX-03
----
+
[source,console]
----
AFX-03
AFX-02         true     Connected to AFX-02
----
+
[source,console]
----
AFX-04
AFX-01         true     Connected to AFX-01
----
+
[source,console]
----
4 entries were displayed.
----

. During giveback, verify if performance has changed for currently running workload (throughput, CPU utilization, IOPS, etc.) and if operations have experienced noticeable disruption. Operations using stateful NAS (such as SMB and NFSv4.x) will experience some disruption due to locking exchange. Use the steps in the performance monitoring test plan.

. Check the home status of the network interfaces.
+
[source,console]
----
AFX::> net int show -is-home false
----

. If the interfaces are not at home, revert them.
+
[source,console]
----
AFX::> net int revert *
----

. After giveback is complete, verify the volume locations.
+
[source,console]
----
AFX::> set advanced
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-01
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-02
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-03
AFX::*> vol show -fields node,size,constituent-count -is-constituent true -node AFX-04
----

. View the volume move status.
+
[source,console]
----
AFX::*> vol move show -vserver svm1 -instance
----

a| *Expected outcome(s):*

* The selected node will panic.
* Cluster will send AutoSupport to NetApp support.
* Cluster will perform give back to normal operations.
* Storage failover should not interrupt operations.
* Volumes should move across nodes to balance performance in between 17-22 minutes after failover.
* Performance should not see a noticeable decrease once volumes are moved.
* Givebacks should rebalance volumes and performance back to the initial state.
* Volumes will not necessarily return back to the same nodes they originated on.
| *Test results:*

| *Test summary:*

| *Comments:*

|===

*Note:* Optional tests 13-16 (FlexCache, S3, Snapshots/SnapMirror, NDU) are linked from xref:test-plans.adoc[Test Plans Overview].

// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:test-11-compute-scaling.adoc[< Previous]
>| xref:test-flexcache.adoc[Next >]
|===
// navigation-links:end
