= Test 5: Volume management
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book

xref:test-plans.adoc[← Back to Test Plans]

[[volume-management]]
== Volume management

NetApp AFX makes some changes to how volumes are created and managed. This test aims to display some of those changes, show scale, and how volumes move automatically.

[cols="1"]
|===
| *Test plan 5 - Volume management*

a| *Test procedure:* +
. Use the script found in the appendix to create a large number of volumes on the cluster. Review the location of the constituent volumes of the FlexGroup volumes. Note the balance of volume counts per node. Volume counts should be relatively evenly distributed (+/- 2).
+
[source,console]
----
AFX::> vol show -volume name* -is-constituent true -fields size -node [node-name]
Example:
AFX::*> vol show -node AFX-01
…
98 entries were displayed. << SVM root is the +1
----
+
[source,console]
----
AFX::*> vol show -node AFX-02
…
97 entries were displayed.
----

. Create a new volume FlexGroup on a dedicated aggregate in admin privilege. Note the error.
+
[source,console]
----
AFX::*> set admin
----
+
[source,console]
----
AFX::> volume create -volume fg1 -aggr-list dataFA[tab] -aggr-list-multiplier 20
----

. Error: command failed: Aggregate "dataFA_2_p0_i1" cannot be used to create a volume on this platform.

. Create a new FlexGroup volume on a specific node’s virtual aggregate using the -aggr-list-multiplier flag in diag priv. Use tab completion to suggest one of the virtual data aggregates.
+
[source,console]
----
AFX::> set diag
AFX::*> volume create -volume fg1 -aggr-list dataFA[tab] -aggr-list-multiplier 20
While NetApp AFX no longer leverages aggregates as a physical construct, there are still virtualized aggregates that “own” volumes. These provide a location for NVRAM commits to occur, since we still write the same way as unified ONTAP. By default, all volumes are created in the Storage Availability Zone and ONTAP handles the volume placement.
View the volume count for each data aggregate after creating the FlexGroup volume. Note that the volumes counts are imbalanced.
AFX::*> aggr show -aggregate data* -fields volcount
aggregate      volcount
-------------- --------
dataFA_2_p0_i1 31
dataFA_4_p0_i1 10
----

. Create a new FlexGroup volume without specifying the aggregate name and check the volume count again. Note how ONTAP is attempting to balance the placement across by placing new volumes evenly across nodes, but the imbalance is still present on the manually placed volumes.
+
[source,console]
----
AFX::*> volume create -volume fg2 -auto-provision-as flexgroup
----
+
[source,console]
----
rtp-afx1k-c01::*> aggr show -aggregate data* -fields volcount
aggregate      volcount
-------------- --------
dataFA_2_p0_i1 41
dataFA_4_p0_i1 20
----

. The imbalance is present because when you manually override ONTAP volume placement, it disables the rebalance functionality (-atm-state). Check that in diag priv.
+
[source,console]
----
rtp-afx1k-c01::*> vol show -vserver svm1 -volume fg1,fg2 -fields atm-state
vserver volume atm-state
------- ------ ---------
svm1    fg1    disabled
svm1    fg2    enabled
----

. That can be re-enabled. Use the following command.
+
[source,console]
----
rtp-afx1k-c01::*> set diag; vol modify -volume fg1 -atm-state enabled
----

. After ~5 minutes, ONTAP runs a job that periodically rebalances the volume counts to even things out. You can either wait for that duration or manually start this process.

. After ~5 minutes, we see this:
+
[source,console]
----
rtp-afx1k-c01::*> aggr show -aggregate data* -fields volcount,node
aggregate      node             volcount
-------------- ---------------- --------
dataFA_2_p0_i1 rtp-afx1k-c01-01 31
dataFA_4_p0_i1 rtp-afx1k-c01-02 30
To manually start the rebalance, a diag level command is used (and is not recommended to use on production workloads unless guided by NetApp support).
AFX::> set diag
AFX::*> debug smdb table atm_kick run
----

. HA failover testing in a later part of this test plan will cover volume rebalancing there as well. If you need to delete volumes/clean up volumes, you can leverage the volume delete script in the Scripts section.

a| *Expected outcome(s):* +
* Volume counts will be balanced across nodes.
* Volume counts will rebalance when uneven.
| *Test results:*

| *Test summary:*

| *Comments:*

|===

// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:test-04-data-migration.adoc[< Previous]
>| xref:test-06-api-testing.adoc[Next >]
|===
// navigation-links:end
