= Test 6: API testing/seamless support for customer automation
:toc: left
:toclevels: 4
:sectnums:
:icons: font
:source-highlighter: highlight.js
:doctype: book

xref:test-plans.adoc[← Back to Test Plans]

[[api-testingseamless-support-for-customer-automation]]
== API testing/seamless support for customer automation

NetApp AFX is intended to provide a seamless ONTAP experience. Included in that is API parity between unified and NetApp AFX so that legacy automation suites using REST API calls to ONTAP will be plug-and-play into NetApp AFX.
If no current API-based automation suites are in use, then some basic REST API calls are provided to test functionality. See the appendix for examples.

[cols="<1",width="100%"]
|===
<| *Test plan 6 - API testing/seamless support for customer automation*

a| *Test procedure:*

. Test your REST API calls against unified ONTAP.

. If you are not already using standard automation REST calls against unified ONTAP, then leverage the example calls in the appendix of this document.

. Test your REST API calls against NetApp AFX. If you are not already using standard automation REST calls against NetApp AFX, then leverage the example calls in the appendix of this document.

a| *Expected outcome(s):*

* REST API calls used with unified ONTAP are tested.
* The same REST API calls are tested against NetApp AFX and are successful, with the exception of SAN-related and aggregate-related calls.
|===

*Note:* Performance testing configuration companion content for Tests 7 and 8 is available in xref:test-07-08-performance-testing-configuration.adoc[Performance testing configuration (Tests 7 and 8)].

// navigation-links:start
[cols="1,1",frame=none,grid=none]
|===
| xref:test-05-volume-management.adoc[< Previous]
>| xref:test-07-customer-workload-real-data.adoc[Next >]
|===
// navigation-links:end
